### ISSUE TITLE
Login fails in deployed app

### ISSUE THREAD

**Issue by willrlin** [CityOfDetroit/bloom#100]
Neither the public nor partner app on the deployed site allows for login. Testing the backend deployment shows that it does return a token when the username/password are correctly sent.

**Comment by willrlin** [comment]
I tested with a dev public build pointed at the deployed backend/core instance and logging in worked fine.

**Comment by willrlin** [comment]
I wonder if it has something to do with the fact that both are deployed to GCP and so trying to address the one from the other is non-obvious? I'm trying to deploy a revision that doesn't route traffic through our VPC.

**Comment by willrlin** [comment]
Nope, that didn't work. Looking at the network tab of chrome inspect it says "blocked:mixed content".

**Comment by willrlin** [comment]
@abbiefarr wondering if you have any ideas here?

**Comment by avaleske** [comment]
Notes from #58 might apply here too?

**Comment by willrlin** [comment]
It doesn't _seem_ like it's the same thing there, because both the client and the server are trying to hit the same (externally available) backend URL. And my local public site can connect and login to the deployed backend no problem.

**Comment by willrlin** [comment]
@avaleske do you know anything about mixed content and why chrome might block that? It doesn't even seem like the request actually gets sent.

**Comment by abbiefarr** [comment]
This is the error I see when I inspect the page and look at the console logs:

`commons.4033a4dbc4167a9e900f.js:1 Mixed Content: The page at 'https://sites-partners-tj3gg4i5eq-uc.a.run.app/sign-in' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://backend-core-tj3gg4i5eq-uc.a.run.app/auth/login'. This request has been blocked; the content must be served over HTTPS.`

Seems like it could be a certificate issue (based on [this](https://stackoverflow.com/questions/37387711/page-loaded-over-https-but-requested-an-insecure-xmlhttprequest-endpoint)). Also it doesn't appear to be specific to Chrome, I tried logging in on firefox and saw the same error.

**Comment by willrlin** [comment]
So it seems like maybe it's trying to load the site from http:// instead of https://, but I don't see how to control that in the code. The only thing I've seen related to certificates and SSL is in the [ormconfig](https://github.com/CityOfDetroit/bloom/blob/main/backend/core/ormconfig.ts), which I don't think is the issue here.

**Comment by willrlin** [comment]
I asked a question in the Bloom repo: https://github.com/bloom-housing/bloom/discussions/1400#discussioncomment-944841

**Comment by willrlin** [comment]
I just realized that the default inside the Dockerfile for sites/public is `http://` to our backend site, but the variable I overrode it with in production is `https://`. Changing the variable in production to `http://` didn't fix the problem, but I wonder if the mixed content is because the build time generated html has some `http://` references to the backend site. I will try to confirm this by building a production container of `sites/public` with `http://` versus `https://`.

**Comment by willrlin** [comment]
When I change it locally and try to login using the production docker container, it now gives me a CORS error.

**Comment by willrlin** [comment]
Although I just tried again and the error went away. I'm hopeful that changing it fixes it for the production site and I just had something slightly incorrect in my Docker container setup.

**Comment by willrlin** [comment]
Fixed now in the deployed app.
