### ISSUE TITLE
Fix Users Invite Flow 

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1001]
Acceptance Criteria
* When I go to the users page, I can see a list of partner users and the ability to add users 
* When I click add users, I can invite a new user to the system 

### QA Review
1. go to https://detroit-partners-dev.netlify.app/users
2. see that the list loads
3. invite users

**Comment by seanmalbert** [comment]
This will fail on staging at the moment, because there are no listings (technically because there are no jurisdictions, which we get from the assigned listings). So if we need to be able to invite users without assigning listings, we'll have to fix that.

**Comment by kathyccheng** [comment]
Okay that's not a problem, lgtm on dev
