### ISSUE TITLE
Listing Table Updates

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1008]
As an admin or partner in Detroit 
I want to see the list of listings table in Partners with columns that are more relevant to me 
So that I can manage the higher load of listings 

**Acceptance Criteria**
* When I am on the list of listings page in Partners, then I should see the following columns - Listing Name, Listing Address, Listing Status, Verified 
* When I am on the page, then I should be able to update the default number of rows 
* When I am on the page, then I should be able to sort by Listing Name, Listing Status and Verified and it should work across pages 

**Notes**
* Update columns 
* For the Listing Status column, we should update the translation keys - Pending should be Draft, Active should be Public, Closed should be Closed 
* Add sorts for Listing Name, Listing Status, Verified 
* Add the ability to change the default view 
* Don't worry about the filter for right now

**Designs** 
https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=5278%3A174361

**Comment by kathyccheng** [comment]
Waiting on sorting across pages

**Comment by dominikx96** [comment]
@seanmalbert I see that backend changes are only in core, so to implement frontend changes we need to merge these into this repo.

**Comment by seanmalbert** [comment]
I'm not entirely convinced that I like the solution presented in core at this time, so I opened https://github.com/CityOfDetroit/bloom/pull/1232, which handles our needs for Detroit.
