### ISSUE TITLE
Add Program labels to Detroit Browse page 

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1011]
**Acceptance Criteria**
* The only label on the image is now Verified 
* The other labels for Accessibility + Programs will go above the summary table

**Notes**
* Remove accessibility off of image 
* Add programs to new treatment in addition to accessibility 
* Community types has no label now 
* This will just cover specifying accessibility + program tags in Detroit
* Dependent on Issue https://github.com/CityOfDetroit/bloom/issues/975

**Designs**
https://www.figma.com/file/D2fNPS5Ucll8uz7hyMUQGB/bloom-public-single-listing?node-id=1238%3A20591

**Comment by emilyjablonski** [comment]
QA Notes:
https://detroit-public-dev.netlify.app/

Add a listing with programs and accessibility features and ensure the tags display as expected.

**Comment by kathyccheng** [comment]
LGTM
