### ISSUE TITLE
Remap Neighborhood to Region

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1014]
**List of Neighborhoods** 
Airport Sub area 
Barton McFarland area
Boston-Edison / North End area 
Boynton
Campau / Banglatown 
Dexter Linwood
Farwell area 
Gratiot Town / Kettering area 
Gratiot / 7 Mile area
Greater Corktown area 
Greater Downtown area
Islandview / Greater Villages area 
Jefferson Chalmers area
Livernois / McNichols area
Morningside area 
North Campau area
Northwest / Grand River area
Northwest University District area
Palmer Park area 
Russell Woods / Nardin Park area 
Southwest / Vernor area 
Warrendale / Cody Rouge area
West End area

**List of Regions**
East Side
Greater Downtown
Southwest
West Side

**Neighborhood to Region Area Mapping** 
https://docs.google.com/spreadsheets/d/15KIX_wSuKmrtjYYrgRgb-LN1cdxIIJ9RSffPJ7SQ7j4/edit#gid=1612299484

**Comment by kathyccheng** [comment]
@pbn4 this is ready

**Comment by kathyccheng** [comment]
Okay I think this is looking good for the most part

**Comment by kathyccheng** [comment]
@pbn4 can you take another look at this? I see the region values in the db in prod, but don't see any of them represented in partners

**Comment by seanmalbert** [comment]
This is on dev now.

**Comment by kathyccheng** [comment]
I think this is good, but will do another check on prod
