### ISSUE TITLE
Update Filters

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1015]
**Acceptance Criteria**
* Update queries for the following filters we want to implement 

**Notes**
* We can update the front end later 
* Community Buildings should be programs
* Bedroom types might need updating based on unit groups
* Regions may or may not currently work 
* Add verified 

![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/b5b1b808-1ffd-448e-bce4-808abb19a239)

**Comment by pbn4** [comment]
> Regions may or may not currently work

@kathyccheng @seanmalbert Currently regions are simply strings in column `neighborhood` in listing. To make it work we have to probaly run a script to map existing database value to those 5 regions from the screenshot, am I understanding this right?

**Comment by kathyccheng** [comment]
@pbn4 the Google team had done something like this: https://github.com/CityOfDetroit/bloom/blob/main/ui-components/src/helpers/regionNeighborhoodMap.ts
