### ISSUE TITLE
Rent price filtering

### ISSUE THREAD

**Issue by willrlin** [CityOfDetroit/bloom#102]
(Split this ticket into multiple, for tracking. It's now
- #102
- #320 
- #321 
- #322 
- #324 )

This is blocked on how we store rent data, and how we want users to filter on it.

The table in the design doc has additional thoughts about how this filter might be structured:
https://app.box.com/integrations/googledss/openGoogleEditor?fileId=839071952572&trackingId=3#heading=h.gnp30ny3nbk3

**Comment by willrlin** [comment]
TODO: add checkboxes for ones that are not blocked by unit summary table, separate tickets for ones that are.

**Comment by kar-r-green** [comment]
Awaiting feedback from HRD to finalize filter requirements. Please standby.

**Comment by willrlin** [comment]
I think this is unblocked now, because we're using AMI percentages to determine what the user can afford, and we're assuming we'll have AMI unit information for most of the properties from HRD's spreadsheet.
