### ISSUE TITLE
Detroit: Management section on individual listing detail shows even if empty

### ISSUE THREAD

**Issue by emilyjablonski** [CityOfDetroit/bloom#1043]
**Acceptance Criteria**
* When I don't specify a management company, then the section shouldn't show

![Screen Shot 2022-03-10 at 6.13.52 PM.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/a49f644d-bd79-43d1-8ece-2439b2c02a42)

**QA notes**
1. Open partners portal: https://deploy-preview-1401--detroit-partners-dev.netlify.app/
2. Fill the "Leasing Agent" section and click preview
3. Make sure the section exists
4. Remove all values from the "Leasing Agent" section and click preview
5. Make sure the section is hidden

**Comment by kathyccheng** [comment]
LGTM
