### ISSUE TITLE
Jurisdiction is not being automatically set on listing form

### ISSUE THREAD

**Issue by emilyjablonski** [CityOfDetroit/bloom#1052]
If a user only has access to one jurisdiction (and thus they don't see a jurisdiction dropdown), the form is not automatically setting the jurisdiction to Detroit, which means that if this user tries to update a field that pulls from jurisdictional items (like programs/community types) nothing loads.

**Comment by seanmalbert** [comment]
Fixed with https://github.com/CityOfDetroit/bloom/issues/1080
