### ISSUE TITLE
Detroit: Summary Tables on Browse

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1059]
**Acceptance Criteria**
* When I am on the Browse page, then I expect to see the Unit Type, Rent, Availability summary table

**Notes**
* Right now, these tables aren't working on the Browse page
* The query should be similar to what's on the listing page

https://www.figma.com/file/D2fNPS5Ucll8uz7hyMUQGB/bloom-public-single-listing?node-id=1238%3A20591

**Comment by seanmalbert** [comment]
@dominikx96 ,
After looking at the backend a little more, I found that we did need to do some work to get the unit group summaries needed for the browse and filter pages. Take a look at `getUnitGroupSummary` used in `sites/public/src/ListingView.tsx` and that should basically get you what you need with little modification. Also note that there are two pages `sites/public/pages/listings.tsx` and `sites/public/pages/listings/filtered.tsx` query listings separately, with the latter used when you filter listings on the public site.

@pbn4 , I opened a PR with the backend changes, so Dominik wouldn't be blocked. Could you please review that and @dominikx96 , you should be mostly good to base your PR for this off of that.

**Comment by seanmalbert** [comment]
The PR mentioned above has been merged.

**Comment by emilyjablonski** [comment]
QA Notes: 

Open the public site and check listing tables
Modify data using partners portal and validate values in the tables

The listing detail page has already been done, so you can also compare the directory page tables with the detail tables.

**Comment by kathyccheng** [comment]
Looks good!
