### ISSUE TITLE
Detroit: Homepage & Site Footer Updates

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1060]
**Notes**
* Update styles
* Add Notifications and Resource CTAs 
* Drop Eligibility Quiz CTA
* Drop Latest section for now 
* Add Rentals link

**Design:** 
https://www.figma.com/file/tUtgsJO8XnF9Ij2dwu22EF/bloom-public-general?node-id=1531%3A7785

## QA Notes:

Design update already signed off by Jesse, but you can verify on dev: https://detroit-public-dev.netlify.app

**Comment by kathyccheng** [comment]
@jaredcwhite sorry I may have an outdated design link, can you use this one? It should be pretty similar, but some updates to things like the footer 

https://www.figma.com/file/D2fNPS5Ucll8uz7hyMUQGB/bloom-public-single-listing?node-id=1249%3A18640

**Comment by jaredcwhite** [comment]
@kathyccheng The "homepage" part of the link you shared there is different than the link in the issue description. Can you confirm I'm _only_ working on homepage changes based on the first link, and the second link is _only_ relevant for the footer itself? TY!

**Comment by kathyccheng** [comment]
LGTM
