### ISSUE TITLE
Detroit - Add Coming Soon to Partners

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1075]
**Acceptance Criteria**
* When I am in the Partners Portal, then I will see a section for Application Date
* Under Application Date then I will see the option to designate Marketing Type
* If they select, Coming Soon, then they will see an option to add Season and Year 
* When I Save Marketing or Coming Soon, then I will see that represented in the summary in Partners 

**Notes**
* We need to add a new field to the listing, Season as a string. The Year will save to the current marketing date 
* Ignore the application due date right now and open house right now, keep them hidden

**Designs**
Edit
https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=5584%3A178462

View
https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=5541%3A176254

**Comment by kathyccheng** [comment]
@slowbot can you add a mockup for the summary view once you've added coming soon + season/year?

**Comment by emilyjablonski** [comment]
QA Notes: The new marketing selection fields should match the mocks. You should be able to add, change, and remove marketing status from a listing.

**Comment by kathyccheng** [comment]
LGTM
