### ISSUE TITLE
Detroit: Update summary tables to include Coming Soon

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1076]
**Acceptance Criteria**
* When I am on the browse page, and a listing is marked as coming soon then I will see Coming Soon in the summary table under availability 
* When I am on the listing detail page, and the listing is marked as coming soon, then I will see Coming Soon in the summary table in the availability section

**Designs**
https://www.figma.com/file/D2fNPS5Ucll8uz7hyMUQGB/bloom-public-single-listing?node-id=1838%3A19822

**Comment by emilyjablonski** [comment]
QA Notes: Add a listing where the marketing status is coming soon, and for every unit group in the unit summary table on the directory and detail page, the availability column should read Coming Soon

**Comment by kathyccheng** [comment]
@emilyjablonski I can't test this on the browse page because it doesn't seem to be updating, maybe something with caching? but looks good on the listing detail page

**Comment by kathyccheng** [comment]
LGTM
