### ISSUE TITLE
Detroit live's partner portal listing page pagination issues

### ISSUE THREAD

**Issue by YazeedLoonat** [CityOfDetroit/bloom#1078]
STEPS TO REPRODUCE:
1. we will be using detroit's live site to look at data
2. log into detroit live's partner portal using an admin log in
3. look through the listing's grid, you'll notice that some listings are repeated and some listings that should show in this grid do not

it has something to do with how pagination of listings is happening in the `list` function in `listings.service.ts`

EXPECTED RESULTS:
Ideally all the listings show up once in the listing grid

OBSERVED RESULTS:
currently duplicate listings show up, and some listings are missing entirely

ADDITIONAL INFORMATION:

### QA Review Notes:
Once this is on https://detroit-partners-prod.netlify.app/, follow the steps to reproduce. You shouldn't see duplicates and missing listings like `Penrose Village - 4f6af8df-1abf-4650-b548-850d94c85a22` and `Gratiot Woods Co-op Senior Apartments - 214ccb4c-0d0b-4ff6-b420-ed05bae0e22e` should now be visible in the list.

**Comment by kathyccheng** [comment]
LGTM
