### ISSUE TITLE
Detroit - Update sort order for listings 

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1091]
**Acceptance Criteria**
* When I am looking at the list of listings on the browse page, then I want to see the coming soon at the top of the list, secondarily sorted by last updated 

### QA Review Notes
1. on https://detroit-public-dev.netlify.app/listings, you should see the listings marked with coming soon at the top of the page and secondarily ordered by last updated
2. also, in the pagination section the "show" option should now work

**Comment by YazeedLoonat** [comment]
I think this will also cover https://github.com/CityOfDetroit/bloom/issues/1125

**Comment by kathyccheng** [comment]
LGTM
