### ISSUE TITLE
Detroit - Clean Up Account Creation

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1094]
**Acceptance Criteria** 
* When I go to create an account, I should not see the option to opt into email notifications or text notifications 

**Notes**
* We will be handling notifications separately 

![image](https://user-images.githubusercontent.com/3453407/160924262-c94f3c04-b6e3-42c5-88af-7a91b566a907.png)

**Comment by emilyjablonski** [comment]
QA Notes:
Try to create an account - you shouldn't see subscription checkboxes
Log in and open the edit account form - you shouldn't see subscription checkboxes
You should be able to save your settings, esp. testing the email and phone fields

**Comment by emilyjablonski** [comment]
@kathyccheng Something to look into for the future is it seems like when this PR was automatically connected to the GitHub issue and the PR was merged, it automatically moved the issue to closed so it skipped the QA column

**Comment by kathyccheng** [comment]
This is good
