### ISSUE TITLE
Detroit - Show Not Available when information not present

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1098]
**Acceptance Criteria**
* When I'm looking at the rent summary table on the listing detail page and the browse one, if rent or AMI information is not present, show Not Available instead of blank 

**Design** 
https://www.figma.com/file/D2fNPS5Ucll8uz7hyMUQGB/bloom-public-single-listing?node-id=1838%3A19822

**Comment by emilyjablonski** [comment]
QA Notes: Add a listing with a unit group that has no rent or ami information and ensure that in the unit summary tables on the directory and detail pages that that cell does not show blank but instead Not Available

https://detroit-public-dev.netlify.app/

**Comment by kathyccheng** [comment]
LGTM
