### ISSUE TITLE
Detroit - Add 1/2 bath option to bathroom dropdown

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1106]
**Acceptance Criteria**
* When I go to add unit group data, the dropdown show show a 0.5 and 1.5 option in addition to 1, 2,3 etc  for both min and max bathroom dropdowns

**QA NOTES**
navigate to: https://detroit-partners-dev.netlify.app/
go to create or edit a listing
fill in all fields required to save
under `Add Unit Group` add a unit group, and notice the new .5 and 1.5 bathroom options are available
select one or both of those
save the listing
verify the detail page shows the bathrooms correctly

**Comment by seanmalbert** [comment]
The field uses a helper called `numberOptions` to populate the options, which will not accommodate these additions as is.

**Comment by kathyccheng** [comment]
LGTM
