### ISSUE TITLE
Detroit - Remove phone number validation

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1123]
**Acceptance Criteria**
* When I create an account and don't give a phone number, then I should still be able to successfully create an account 

**Notes**
* Looks like it requires a valid phone number right now 

![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/9a7a42de-8ea9-4d65-b669-2d6ac4b678f9)

**Comment by seanmalbert** [comment]
Creating an account - https://detroit-public-dev.netlify.app/create-account

**Comment by adriencyberspace** [comment]
QA Notes:

Entry Point: http://localhost:3000/create-account

Create a new account with all required fields. Do not include a phone number. Sign up should be successful.
