### ISSUE TITLE
Detroit: Add link for notification page 

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1147]
**Notes**
* Right now it's a placeholder, but this is the actual link for Sign Up today: https://public.govdelivery.com/accounts/MIDETROIT/subscriber/new?topic_id=MIDETROIT_415

**Comment by emilyjablonski** [comment]
QA Notes: On Detroit dev, ensure the homepage Sign Up Today button goes to the URL in the issue
