### ISSUE TITLE
Detroit - Browse page not updating 

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1151]
**Notes**
* When I post a new listing or update information for a live listing, the browse page doesn't seem to be updating 
https://detroit-public-dev.netlify.app/listings

**Comment by seanmalbert** [comment]
The nginx proxy needed to be updated. The browse page on https://detroit-public-dev.netlify.app/listings now updates. Like before there is a 60 second delay for cache revalidation.

**Comment by kathyccheng** [comment]
LGTM
