### ISSUE TITLE
Partners - Waitlist not saving properly

### ISSUE THREAD

**Issue by seanmalbert** [CityOfDetroit/bloom#1161]
From Vu-Bang:

For the Elite Property property manager, when we update her unit types from “Closed waitlist” to “Open waitlist”, when I made the update, it shows up as “Open waitlist”. But checking in a day later, it shows up as “Closed waitlist” now. Was doing this for Charlmers Square. When I originally went in to edit back to open, “open waitlist” was checked. And when I saved and went back, “closed waitlist” was checked again.

![Screen Shot 2022-04-19 at 9 28 08 AM](https://user-images.githubusercontent.com/4401157/164491853-92c139fe-28eb-4ecc-b935-76b45bff7b3a.png)

**Comment by emilyjablonski** [comment]
QA Notes: You should be able to: Save a listing with units groups that have closed and open waitlists, and then open the listing form with closed/open waitlists, don't open any of the forms, just save, and have the waitlist values stay the same.

**Comment by kathyccheng** [comment]
LGTM
