### ISSUE TITLE
Detroit - Follow-up Visual Design Items

### ISSUE THREAD

**Issue by jaredcwhite** [CityOfDetroit/bloom#1165]
Follow-up TODO items from #1134:

- [x] Make max width and margins for language nav the same as the navbar (1)
- [x] Footer: we should increase space between listing questions and general questions to 2rem (2)
- [x] Footer-section component with logo and contact content should have max width of 1024px so text doesn't run too long (3)
- [x] Should have 1px line between the header and the content of the single listing page (5)
- [x] Tooltip has line between bubble and arrow (see below) (6)

![image](https://user-images.githubusercontent.com/3453407/167428683-39bc716f-1657-45db-a31c-ea76dd31fb33.png)

Tacking another issue onto this:
- [x] There is a window size in which the menu icon is not right aligned - maybe larger than sm and smaller than md (4)
![Screen Shot 2022-05-10 at 12 59 30 PM](https://user-images.githubusercontent.com/60076088/167692994-ac3bc7cd-9a59-4748-9cfd-108d7b79686d.png)

**Comment by adriencyberspace** [comment]
QA Notes:

Entry Point 1: https://detroit-public-dev.netlify.app/
1. View header - language nav width and padding the same as navbar width and padding (Note: the border around the Sign Up button and lack of border around the right-most language button create the appearance that they are not aligned)
2. View footer - there should be a 2rem margin below listing questions section
3. Still on footer - left footer section should have a max-width of 1024px
6. Narrow screen width to between 768px and 1024px - the hamburger menu icon should remain right-aligned

Entry Point 2: https://detroit-public-dev.netlify.app/listings
4. Click into any listing - notice a 1px line between the Site Header and the content of the page (Note: I removed the top border of the process container to avoid clashing with the new divider line)
5. Still on listing page, click the tooltip - there should be no 1px border between the tooltip main rectangle and the tooltip arrow

**Comment by seanmalbert** [comment]
#A note for QA:
For the above notes, please QA at https://deploy-preview-1270--detroit-public-dev.netlify.app/
