### ISSUE TITLE
Page Not Found UI issues

### ISSUE THREAD

**Issue by emilyjablonski** [CityOfDetroit/bloom#1167]
On Detroit there are UI issues with the page not found block. You can trigger this UI by visiting a listing with an invalid id (ie http://localhost:3000/listing/abcd).

We should remove the yellow border around the button and make the text white so it is readable. (@slowbot please feel free to update the AC!)

![Screen Shot 2022-04-22 at 5.48.21 PM.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/694122b6-7d89-411b-9879-0ab23759e959)

**Comment by adriencyberspace** [comment]
QA Notes:

Entry Point: any bad link i.e. http://localhost:3000/listing/abcd 

Text should be white and readable over the green background. Unnecessary borders / background colors around button should not be there.
