### ISSUE TITLE
Mobile listing section images overlapping text in Arabic

### ISSUE THREAD

**Issue by emilyjablonski** [CityOfDetroit/bloom#1168]
On the listing detail page on mobile, the icons for each of the dropdown sections overlap the section text.

![Screen Shot 2022-04-22 at 6.12.37 PM.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/0c6bffe6-ee7b-4a44-8a6f-a9f1c9620885)

**Comment by adriencyberspace** [comment]
QA Notes:

Entry Point: http://localhost:3000/listings

1. Click into any listing and enable Arabic as your language
2. Scroll down to the listing sections (i.e. Process, Listings, Neighborhood) and minimize your screen to mobile width - you should see that the the Icons are no longer overlapping with the dropdown svg: ![Screen Shot 2022-04-26 at 4 35 46 PM](https://user-images.githubusercontent.com/60076088/165396552-72bab209-88f7-4fbf-ad42-a40de21999c4.png)
3. Check this in a non right-to-left language and it should look as it did before
4. Check desktop view in Arabic - the layout should be the same as it is on dev
