### ISSUE TITLE
Fix RTL language padding on listing detail page

### ISSUE THREAD

**Issue by emilyjablonski** [CityOfDetroit/bloom#1192]
The left/right margin on the main listing detail section needs to swap in RTL.

There should be no margin on the right - the image should be flush with the browser.
![Screen Shot 2022-04-27 at 2.04.02 PM.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/1dd97052-b605-45c2-aaa4-15a482a60ca8)![Screen Shot 2022-04-27 at 2.03.56 PM.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/6b2a9bbd-14e1-43a8-9def-2added83b0aa)

**Comment by adriencyberspace** [comment]
QA Notes:

Entry Point: https://detroit-public-dev.netlify.app/listings

1. Click into any listing page in desktop view
2. Switch between English and Arabic and you should see that the paddings / margins around the main image and the Process section are consistent between the two views.

![image](https://user-images.githubusercontent.com/60076088/166253035-6d9c1fba-31ce-4daa-bede-98b7287e2735.png)
