### ISSUE TITLE
Tooltip UX issues

### ISSUE THREAD

**Issue by emilyjablonski** [CityOfDetroit/bloom#1194]
(1) If you have the tooltip open and scroll before you move your mouse the tooltip stays open for a few seconds, and if you are focused on the info icon which opens the tooltip it stays open for the whole time you scroll
https://images.zenhubusercontent.com/360584111/e5e45f03-1828-4bf7-9a0f-d8176686fd5a/scroll_tooltip.mov

(2) If you click on a tag on the image card on the directory page the tooltip flashes before you are redirected to the details page

**Comment by adriencyberspace** [comment]
QA Notes:
