### ISSUE TITLE
Region options on the main page doesn't filter properly

### ISSUE THREAD

**Issue by YazeedLoonat** [CityOfDetroit/bloom#1198]
STEPS TO REPRODUCE:
1. head to https://detroit-public-dev.netlify.app/
2. on that page there are the region options, if you click on one you should navigate to a filter version of the listing grid. Filtered by the region selected
3. this filtering doesn't occur

EXPECTED RESULTS:
Clicking on those region options should take you to a correctly filtered set 

**QA NOTES**
**Testing new coming soon filter** (https://detroit-public-dev.netlify.app/listings)
Head to public site, go to view all listings and opt to add a filter
there should be a new coming soon under availability that is functional 

**Fix for region options** (https://detroit-public-dev.netlify.app/)
Head to the root page for the public site
notice at the bottom there are the regions laid out in a carousel
Click on one of the region options
the filter should function properly and should play nicely with the new filter form

**Comment by kathyccheng** [comment]
LGTM
