### ISSUE TITLE
Filtering does not show results, but indicates there are results

### ISSUE THREAD

**Issue by emilyjablonski** [CityOfDetroit/bloom#1201]
Currently on dev, if you select Vacancies and Open Waitlist it has the below strange UI which indicates that there is one result but it does not show. I'm not sure what is causing this, so part of this may need to be exploring repro steps if the data on dev were to change and cause this to not happen anymore.

![Screen Shot 2022-04-28 at 3.39.32 PM.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/890ca667-3777-45d5-a307-f1a7a78a3e5e)

**QA NOTES**
https://detroit-public-dev.netlify.app/
Select `Vacant Units` as the filter, the listings that appear should all have vacant units and the number of listings appearing should match the number of total listings displayed (`Page 1 of 1(3 Total Listings)` should have 1 page and 3 listings for example)

**Comment by kathyccheng** [comment]
LGTM
