### ISSUE TITLE
Rent filters do not include listings with no rent data

### ISSUE THREAD

**Issue by emilyjablonski** [CityOfDetroit/bloom#1203]
When you include a minimum or maximum monthly rent value in the filters, listings that do not have available rent data are excluded from the results.

We're not sure if this is expected behavior. (1) We include listings with no available rent data when filtering, acknowledging they may or may not have a rent value within the range but we are showing them what we know (2) We continue to exclude listings without available rent data when filtering on a rent value and ensure we are only showing them listings we are confident fit the filtered value.

**Comment by kathyccheng** [comment]
duplicate
