### ISSUE TITLE
Long load times for filtering

### ISSUE THREAD

**Issue by emilyjablonski** [CityOfDetroit/bloom#1205]
It is inconsistent, but you can reliably experience a long load time for filtering (relatively long, but it is a few seconds when it should be almost instantaneous especially considering there are <15 listings in the tested cases).

Example repro steps:
* Add a single unit type filter, submit
* Add a single availability filter, submit
* Add the verified filter, submit
.... etc ....

Most of the time it is instantaneous, but sometimes it takes a few seconds.

https://images.zenhubusercontent.com/197330191/3bae64a7-4430-4f03-98d5-72ebceaaca2d/screen_recording_2022_04_28_at_5_25_27_pm.mov

**Comment by YazeedLoonat** [comment]
@emilyjablonski @seanmalbert I wasn't able to replicate this issue anymore, from request by Sean though I did do some testing using a few different criteria. It ended up looking jank in github comment, so I created: https://docs.google.com/document/d/1ociGod-_0KxbOTAeCbO6-Wq0p9tiEGgA3Dk6Xc2xStg/edit?usp=sharing

to help explain my findings. I'm not sure if any of that helps either of you, but if you have any questions or wanna talk about it lemme know

**Comment by seanmalbert** [comment]
@YazeedLoonat , as discussed, let's make these updates in parts:

1. Create new views as slim as they can be, one for public browse/filter pages and one for partners and update the sites to use them
2. update listings.service list to run the inner query to fetch the IDs and pass those into the main query, if there is no filter we can skip the inner filter query
3. the theory is that we now may be able to query unit groups as part of the main query, illuminating the need for the query in `addUnitSummariesToListings`

**Comment by kathyccheng** [comment]
Closing, remaining work in #1390 and #1391
