### ISSUE TITLE
Inconsistent casing in unit summary tables

### ISSUE THREAD

**Issue by emilyjablonski** [CityOfDetroit/bloom#1226]
![Screen Shot 2022-05-03 at 9.49.22 AM.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/3dd78490-51b3-44e3-88b4-889b6f502db4)

To be consistent with the other labels, it should read `Vacant units` / `Vacant unit`

**Comment by adriencyberspace** [comment]
QA Notes:

Entry point: https://detroit-public-dev.netlify.app/listings/

1. Find a listing with 1 vacant unit
2. Find a listing with 2 or more vacant units
3. Find a listing with 1 or more vacant units AND a closed waitlist
The casing should be 'Uppercase lowercase' and layout should look like this: 
![image](https://user-images.githubusercontent.com/60076088/169326945-268ddb39-9cc1-4e82-a314-fede29095bf3.png)](http://localhost:3000/listings/)
