### ISSUE TITLE
Detroit - Digital application showing up 

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1244]
**Acceptance Criteria** 
* When I am in Detroit Partners on the applications tab in listings mgmt, I should not be able to choose to use the common application 

**Notes**
* Keep question is there a digital application or not. If they select Yes, then show URL. 
* Remove Do you want to use the common application question. The conditional for showing the URL should be removed from that question and placed on the first one. 
* I would maybe also clean up all of the current values in the DB if possible? It might be really confusing down the road for when we do re-introduce Common App back

**Comment by emilyjablonski** [comment]
QA Notes: Ensure the common app question is removed from partners, that you can add/remove a custom app URL, that those links open in a new tab, and that once the migration has run (after deploying), any listings that might have had common app set to true are set to false.

**Comment by kathyccheng** [comment]
LGTM
