### ISSUE TITLE
Detroit - Page Not Found Errors

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1245]
When interacting with the browse page, filters, and the pagination /show default number, there were a lot of page not found errors with client side exception errors 

I wonder if it has to do with the URL params staying on page 1? 

https://detroit-public-prod.netlify.app/listings/filtered?page=1&limit=8&status=active&availability=&region=&accessibility=&bedRoomSize=SRO,threeBdrm&communityPrograms=d1c2eba9-09ab-4dc6-8e24-d9576ce3cca9,4928c38b-b7b5-4c15-9a75-98ab9c59b10e

## QA Notes
This should now not be reproducible on https://detroit-public-prod.netlify.app/

**Comment by sheneral** [comment]
Once I encountered the page not found error while using the filter, it is happening across other languages also even after refreshing the page, even when filters are not applied.

With no filters applied, after clicking next page on the first page, it says page not found. This happens for English, Spanish, Arabic, and Bengali.

**Comment by kathyccheng** [comment]
LGTM
