### ISSUE TITLE
Detroit - assorted mobile fixes

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1252]
**Assorted Fixes** 
* When I switch to Arabic and then back to English, RTL remains until refresh. It should switch automatically (Safari and Chrome on iOS)
* Add space between rent options on mobile (see image below below $450 per month and 30% income)

![image](https://user-images.githubusercontent.com/3453407/167434763-5274d1d7-77d4-4612-a22b-a876021ab90c.png)

**Comment by adriencyberspace** [comment]
Entry Point:  https://detroit-public-dev.netlify.app/listings

Issue 1:
1. Visit entry point on Safari
2. Switch language to Arabic
3. Switch language back to English (or other non-RTL language)
4. Notice that page layout is properly displaying left-to-right

Issue 2:
1. On same page, minimize window to mobile width
2. Notice that there is space between the after the comma between $ per month and % income:
![Screen Shot 2022-05-10 at 11 53 52 AM](https://user-images.githubusercontent.com/60076088/167688093-96cbc637-3e88-4e7c-bf69-2ee9b0ef7293.png)
