### ISSUE TITLE
Detroit - Final Translation Fixes

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1253]
Notes
* Remaining missing strings (some are for all languages and some are for just one language)
* https://docs.google.com/spreadsheets/d/1xmKVwpgz-gpEazjwtY6xPYy2Tb5zPKig3mWAPPFLmas/edit#gid=0e 
* Add program translations based on the program's title (for now, before we add google translate to the directory page)
* Arabic language is showing one footer string in bengal
![image](https://user-images.githubusercontent.com/3453407/167435912-1281dc46-c793-4d37-a650-808731ab273c.png)

**Comment by emilyjablonski** [comment]
QA Notes: Ensure the new translations are added.
