### ISSUE TITLE
Detroit - Empty Developer String

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1254]
**Acceptance Criteria**
* When I add a paper application with application send to addresses, but I don't specify a developer name, it should say "Developer is not responsible for lost or delayed mail"

**Comment by emilyjablonski** [comment]
![image (6).png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/4c40a443-9343-45c2-a363-f0f6b6268312)

**Comment by seanmalbert** [comment]
We got this in on the last production release, so this can be reviewed on https://homeconnect.detroitmi.gov/

**Comment by sheneral** [comment]
LGTM
