### ISSUE TITLE
Android pagination view starts at bottom of page instead of top

### ISSUE THREAD

**Issue by adriencyberspace** [CityOfDetroit/bloom#1269]
When I am on android chrome, when I use the pagination it takes me to the bottom of the page instead of the top.

QA Notes:
Start Here on android device: https://detroit-public-dev.netlify.app/listings
1. Scroll to bottom of the page
2. Click 'next' and see if new page loads at top
3. Scroll to bottom of the new page
4. Click 'previous' and see if previous page loads at top

**Comment by YazeedLoonat** [comment]
LGTM!
