### ISSUE TITLE
Detroit - Show Missing Sections on Listing Detail Page

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1278]
**Acceptance Criteria**
* When I am on public listing detail page, and the listing has the rental assistance section filled out, then it should show as a numbered section 
* When I am on a public listing detail page, and the listing has any of the Additional Eligibility Rules filled out, then it should show 
* When I am on a public listing detail page and the building has additional building selection criteria that should show as well 

**Notes**
* These sections currently aren't showing up - Rental Assistance, Additional Eligibility Rules, Building Selection Criteria 
* The ordering in Detroit should be Household Max Income, Occupancy, Rental Assistance, Community Programs, Additional Eligibility Rules 
* They're numbered, but if a section doesn't have data then should skip to the next number 

**Designs**
This is what they look like on Core
![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/0d30ba4c-9488-4c77-a2cc-a52ed94061ea)
![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/e570554b-3ea8-4257-822c-82b7281bd0a1)

**Comment by seanmalbert** [comment]
### QA Notes
From https://detroit-partners-dev.netlify.app/
1. Run partners and fill the "Additional Eligibility Rules" fields in a listing page
2. Open preview and check if these sections exist

**Comment by sheneral** [comment]
The Eligibility section heading and Household Maximum Income and Occupancy are repeated before continuing with Rental Assistance

![Screen Shot 2022-05-18 at 9 50 55 AM](https://user-images.githubusercontent.com/100251192/169098634-c565f04f-7698-454d-9d66-e6cf8cc9f3fe.png)

**Comment by dominikx96** [comment]
@sheneral @seanmalbert here is a fix: https://github.com/CityOfDetroit/bloom/pull/1282

**Comment by seanmalbert** [comment]
@sheneral , this is ready for QA.

**Comment by sheneral** [comment]
Looks good!
