### ISSUE TITLE
Detroit Mobile - filtering buttons hidden  

### ISSUE THREAD

**Issue by ColinBuyck** [CityOfDetroit/bloom#1286]
When using Chrome and Safari on an iOS mobile device, the "submit" and "clear" buttons are hidden on the listing filtering drawer. Typically, scrolling down hides the search toolbar but since the drawer's scrolling is not synced with the body of the html it doesn't hide.

QA Notes/Steps to reproduce the behavior:
1. Go to https://detroit-public-dev.netlify.app/
2. Click on 'See Rentals'
3. Click "Filter" button
4. Scroll to the bottom to see if 'submit' and 'clear' are usable.

**Comment by kathyccheng** [comment]
LGTM
