### ISSUE TITLE
Detroit - Clean Up Accessibility Features 

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1290]
**Acceptance Criteria** 
* Accessibility features in Partners should reflect this new list 
* These should show up on the public listing detail page if added 
* These should show up on the filters 
* We should migrate all old listings to this spreadsheet 

**Notes**
* Update accessibility features - yellow for renaming, green for new ones - https://docs.google.com/spreadsheets/d/15KIX_wSuKmrtjYYrgRgb-LN1cdxIIJ9RSffPJ7SQ7j4/edit#gid=2017399755
* Migration script for current listings based off of this spreadsheet - https://docs.google.com/spreadsheets/d/15KIX_wSuKmrtjYYrgRgb-LN1cdxIIJ9RSffPJ7SQ7j4/edit#gid=679319827

**QA Notes**
_on the partner site_
log in and go to edit/create a listing
notice the new features are present on the listing form, and notice that the updated label presents are there 
notice that after the save the detail page has the same updates

_on the public site_
take a look at the listing detail page, and notice that the new/updated features are present
take a look at the listing filter form, and notice that the new/updated features are present
notice that the new features do function in the form

**Comment by kathyccheng** [comment]
LGTM 
@YazeedLoonat we should run the migration once we push this to prod right?

**Comment by kathyccheng** [comment]
LGTM

**Comment by YazeedLoonat** [comment]
[query.txt](https://github.com/CityOfDetroit/bloom/files/8921381/query.txt)
.

**Comment by YazeedLoonat** [comment]
[output.txt](https://github.com/CityOfDetroit/bloom/files/8921436/output.txt)
