### ISSUE TITLE
Detroit - Update what to expect 

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1293]
**Acceptance Criteria**
* If the listing is a coming soon listing, set the default what to expect to the Coming Soon text 
* If the listing is a marketing listing, set the default text to the new what to expect default text 
  * This is an update for the first section and Read More section 
* When it gets merged, re-run script for already set coming soon listings 
* Remove the what to expect + read more sections from partners 

https://docs.google.com/spreadsheets/d/1KmIs93OKQIDsKyay90MLWmItLVBCyAytJJ8s5p-_Zm8/edit#gid=270098974

**Comment by emilyjablonski** [comment]
QA Notes:

Ensure the defaults are properly set on the existing listings and the fields are now gone in partners.

Additionally, ensure that when you create a new listing, the right text is set on both marketing types, and changes when the marketing type changes.

**Comment by kathyccheng** [comment]
LGTM
