### ISSUE TITLE
Test site accessibility

### ISSUE THREAD

**Issue by elenm** [CityOfDetroit/bloom#130]
- [ ] run automated tests - lighthouse
- [ ] test with screen reader
- [ ] test by tabbing through
- [ ] check headings and landmarks (bring up with the screenreader)
- [ ] send automated report to @jedgar1mx

Some checklists to refer to: 
https://www.w3.org/WAI/WCAG21/quickref/
https://webaim.org/standards/wcag/checklist

**Comment by willrlin** [comment]
FYI I added a task after meeting with Edgar - he would like to see any reports we generate and he will check with the Office of Accessibility to see if there's anything else they would like to see before we launch.

**Comment by pfeeny5** [comment]
Accessibility Findings - Sept 13, 2021

Home Page:
Lighthouse - Background and foreground colors do not have a sufficient contrast ratio.
![Screen Shot 2021-09-13 at 12 12 37 PM](https://user-images.githubusercontent.com/82653098/133140534-82cb78c3-7654-467f-a608-76db347a40ec.png)


Tab Navigation: No issues.  “Your Feedback” link in top right doesn’t show green box while navigating around.

Voice Over: 
See Rentals - listed as `link, See Rentals, main`, want to ensure that’s correct
Do I Qualify - listed as `link, Do I Qualify?, article` 

Headings:
- 2: Languages
- 2: Detroit Home Connect
- 2: Navigation Menu
- 1: Find affordable housing inDetroit
- 2: Check in Minutes if You Qualify!
- 2: Footer
- 3: Project information
- 3: Contact information
- 3: Legal information

Landmarks:
- Language navigation
- Main navigation
- Main
- Article
- Footer navigation


Listings Page:
Lighthouse - Background and foreground colors do not have a sufficient contrast ratio.
![Screen Shot 2021-09-13 at 12 12 54 PM](https://user-images.githubusercontent.com/82653098/133140561-5be9adc7-4e26-4e6f-99a0-41bda05a1349.png)


Tab Navigation: No issues

Voice Over: 
`Do I Qualify` listed as Link, not button like `Filter Listings`
`See Details` listed as link, not button
Listing Images listed as article - seems appropriate just want to confirm

Headings:
- 2: Languages
- 2: Detroit Home Connect
- 2: Navigation Menu
- 1: Rent affordable housing
- 2: TREYMORE APARTMENTS
- 2: OAK VILLAGE INDEPENDENCE
- 2: NEW CENTER SQUARE
- …
- 2: Footer
- 3: Project information
- 3: Contact information
- 3: Legal information

Landmarks
- Language navigation
- Main navigation
- main
- article
- article
- …
- Footer navigation

Individual Listing Page:
Lighthouse - Background and foreground colors do not have a sufficient contrast ratio.
![Screen Shot 2021-09-13 at 12 13 06 PM](https://user-images.githubusercontent.com/82653098/133140579-e26fc21f-ad04-4754-9a6b-9f1856cbddd7.png)


Tab Navigation: Order seems a little confusing to me.  View Map -> Call # -> Website -> Apply Online -> Call # -> down to Bedroom tables.  Should we consider moving to the bedroom tables before going to the right hand rail?  So its the entire left column, then the right column?

Voice Over: 
`Apply Online` listed as link, not button
Rooms under feature listed as buttons - seems incorrect

Headings:
- 2: Languages
- 2: Detroit Home Connect
- 2: Navigation Menu
- 2: NEW CENTER COMMONS
- 4: MANAGEMENT COMPANY -- Propose H3
- 2: HOW TO APPLY
- 3: CONTACT MANAGEMENT COMPANY
- 2: Features
- 3: Studio: 11 units
- 3: 1 BR: 22 units
- 3: 2 BR: 12 units
- 2: Neighborhood
- 3: NEW CENTER COMMONS
- 2: Footer
- 3: Project information
- 3: Contact information
- 3: Legal information

Landmarks
- Language navigation
- Main navigation
- main
- article
- complementary
- Footer navigation

**Comment by willrlin** [comment]
Tagging @jedgar1mx FYI for site accessibility report.

**Comment by pfeeny5** [comment]
Partner Portal Accessibility Findings - Sept 14, 2021

**Partner Portal Log In:**
Lighthouse - Background and foreground colors do not have a sufficient contrast ratio.
![Screen Shot 2021-09-14 at 10 44 49 AM](https://user-images.githubusercontent.com/82653098/133285644-117a2faa-793e-47c3-9038-a74061ad13b8.png)


Tab Navigation: No Issues

Voice Over: No Issues 

Headings:
- 2: Detroit Partner Portal
- 2: Navigation Menu
- 2: Partners Sign in
- 3: Legal information

Landmarks:
- Main navigation
- main
- article
- complementary
- Footer navigation

**Partner Portal Summary Table View:**
Lighthouse:
Background and foreground colors do not have a sufficient contrast ratio.
Heading elements are not in a sequentially-descending order
![Screen Shot 2021-09-14 at 10 50 11 AM](https://user-images.githubusercontent.com/82653098/133285535-8f5c3395-50c9-4ab1-9c56-1ef51f968bfa.png)


Tab Navigation: There is a second text link/hidden text field that shows behind the `Add Listing` button.  Noticed while tabbing through.  First gets the hidden field, then the button.
![Screen Shot 2021-09-14 at 10 52 54 AM](https://user-images.githubusercontent.com/82653098/133285466-0f6622f2-4438-4764-9c39-c15cf60e6f55.png)
![Screen Shot 2021-09-14 at 10 53 06 AM](https://user-images.githubusercontent.com/82653098/133285484-8a8737e0-566d-4cba-ad58-7c204b725fd6.png)


Voice Over: Shows `link, Add Listing, article` for hidden field, then `ADD LISTING, button`

Headings:
- 2: Detroit Partner Portal
- 2: Navigation Menu
- 1: Listings
- 3: Legal information -- Propose H2?

Landmarks:
- Main navigation
- main
- article
- Footer navigation

**Partner Portal Edit View:**
Lighthouse - Background and foreground colors do not have a sufficient contrast ratio.
![Screen Shot 2021-09-14 at 11 00 28 AM](https://user-images.githubusercontent.com/82653098/133285309-66c115ff-33d5-4f82-b5c2-c2eec35ddae8.png)

Tab Navigation: 
Not able to goto `Application Process` tab using tab navigation.  Can use arrows from `Listing Details` tab to access. 
![Screen Shot 2021-09-14 at 11 02 24 AM](https://user-images.githubusercontent.com/82653098/133285269-ba1051bb-7caf-4baa-897d-4e40a22a34d5.png)

Not able to access `Custom` radio using tab navigation alone. Can get to `Custom` radio using arrow keys from `Automatic` button. 
![Screen Shot 2021-09-14 at 11 02 29 AM](https://user-images.githubusercontent.com/82653098/133285180-e79364da-2a86-4a3f-bc10-22683442e92f.png)

Only able to access `Individual Units	` radio button when using SHIFT+Tab from `Add Units` button.  Not able to access on forward navigation. Can access similar to above with arrow keys from `Unit Type` radio. 
![Screen Shot 2021-09-14 at 11 02 52 AM](https://user-images.githubusercontent.com/82653098/133285119-0fb5a4ec-5845-43a9-a722-f6922e29877d.png)

Voice Over: Back link displays: `Back and 1 more item and 1 more item, alert, Back, button, main`.  Just want to confirm this is expected.  Also screen reader makes it clear that each of the tabs and radio buttons are 1 of 2 and you can select either.  It was less clear just with tab-navigation.

Headings:
- 2: Detroit Partner Portal
- 2: Navigation Menu
- 1: New Listing
- 2: Listing Intro
- 2: Building Details
- 2: Community Type
- 2: Listing Units
- 2: Housing Preferences
- 2: Additional Fees
- 2: Building Features
- 2: Additional Eligibility Rules
- 2: Additional Details
- 3: Legal information

Landmarks:
- Main navigation
- Main
- Article
- Footer navigation
