### ISSUE TITLE
Detroit - Don't show Paper Application section if no file added 

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1302]
**Acceptance Criteria**
* If I say yes paper application but I don't upload a file, then don't show the paper application section on the public site 

**Notes**
* Right now, if I choose yes to paper application but don't actually have an uploaded asset, then the section shows on the public site but there's nothing to download

**Comment by dominikx96** [comment]
@kathyccheng I created a new ticket in core: https://github.com/bloom-housing/bloom/issues/2845

**Comment by kathyccheng** [comment]
Core piece done
