### ISSUE TITLE
Detroit - Add Utilities 

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1311]
As a resident 
I want to know which utilities are included with rent
So that I have a better sense of how much I need to pay 

Acceptance Criteria
* When I am in partners, I should see a section section asking me to check options for utilities included 
* When I am on the public listing detail page, then I should see the options included in the Additional Fees section 

**Notes**
* We'll need a new field for utilities on the listings model 
* We can hardcode strings for translations
* Requires update to Additional Fees component (which will need to happen in Core)

**Content** 
Refer to the final set of Utilities here row 12, not what's int he designs if they differ
https://docs.google.com/spreadsheets/d/1glJRJ6znXsYJwF2AAI0w6xhN59ebcEMO8Qr0JU2mLnU/edit#gid=270098974

**Designs** 

_Partners_ 
https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=6059%3A181135

_Listings_ 
https://www.figma.com/file/D2fNPS5Ucll8uz7hyMUQGB/bloom-public-single-listing?node-id=2373%3A20712

Testing on Partners https://detroit-partners-dev.netlify.app/sign-in:
Part 1: 
1. Login
2. Select a listing, click edit, and scroll down to ensure that the new utilities form fields are available and clickable
3. After selecting a variety of utilities, click 'save & exit', and then ensure that they are on the detailed view.

Part 2: 
1. Go back to edit the same listing, unselect all options for utilities, and then save the listing again. 
2. The 'Utilities Included' title and bullets should be no longer visible.

Testing on Public https://detroit-public-dev.netlify.app/:
1. Select a listing that you recently marked as having included utilities
2. Observe the bulleted list in the 'Additional Fees' Component. 
3. Select a listing without included utilities
4. Ensure that there is no indication of the previously observed section

Note: If other 'additional fee' messages are available for the listing, the section will be in a 2-column format (with the exception of the bottom row which will fill if there is an odd number of footer info pieces).

**Comment by sheneral** [comment]
looks good
