### ISSUE TITLE
Detroit - Copy Updates

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1314]
Notes
* Should be "Affordable Unit Group Quantity" 
* Currently missing a "d"
* The Edit Programs button should say Edit Communities

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/3453407/172692517-aa16c34a-704c-47f4-b0b6-c9b701bf11f2.png">

![image](https://user-images.githubusercontent.com/3453407/174131157-7d3c3be0-29ca-476c-9146-08dd0109b55b.png)

**Comment by sheneral** [comment]
looks good
