### ISSUE TITLE
Detroit - Support Listings Search 

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1348]
**Acceptance Criteria**
* I should be able to search by listing name on the table of listings in Detroit 

**Notes** 
* Add support for search on listings in Detroit, broken out of last Detroit update from Core 
* In bringing over latest Core code, a lot of changes to how we order listings. Since Detroit diverged a lot, there's more work to get that resolved 

QA Notes: https://detroit-partners-dev.netlify.app/
1. Log in
2. Use the search bar (at least 3 characters)
3. The listings should automatically filter to match the inputted string
Additionally, test all other existing partners table features:
5. Sorting by column
6. Re-ordering the columns
7. Logging out and logging back in to see your most recent table configuration
8. Clicking on rows to see the listings view

**Comment by kathyccheng** [comment]
@ColinBuyck when I enter a listing name, it doesn't look like it's filtering the other options out

**Comment by ColinBuyck** [comment]
@kathyccheng It should be filtering now! I forgot to redeploy the backend after merging this in so the backend changes hadn't been implemented.

**Comment by kathyccheng** [comment]
LGTM
