### ISSUE TITLE
Either keep or remove jsonpath filtering in `GET /listings`

### ISSUE THREAD

**Issue by anders-schneider** [CityOfDetroit/bloom#135]
https://github.com/CityOfDetroit/bloom/issues/56#issuecomment-863578273 has some detail about what `jsonpath` is and how Bloom does/doesn't depend on it. TLDR it lets you do filtering in the backend *after* the DB has returned results, and Bloom doesn't seem to use it anywhere outside of tests.

We have added filtering at the level of the SQL query (https://github.com/CityOfDetroit/bloom/issues/69) and plan to add more filtering that way. We don't plan to rely on jsonpath-filtering.

Additionally, jsonpath filtering (since it happens after the SQL query) messes with pagination: if jsonpath-filtering e.g. removes one or more listings from the result, the pagination metadata will be incorrect.

But, before we remove jsonpath filtering, we should figure out if Exygy plans to rely on it in any way. If they do, and we got rid of it, we'd risk making it more difficult to merge future changes (in either direction) in the ListingService part of the codebase.

If we do opt to keep jsonpath in the query params, we might want to do some parameter-checking to e.g. fail the request if both jsonpath and pagination params are set.

Done criteria: we have either kept/removed jsonpath filtering, and the ListingService code has comments that explain our decision.

**Comment by avaleske** [comment]
As noted [here](https://github.com/bloom-housing/bloom/pull/1578#discussion_r679074004), removing jsonpath will require adding a filter for `listing.property.buildingAddress.county` value.

**Comment by willrlin** [comment]
I think we can close this one; if they want to remove the json path filtering upstream we'll get that in a merge and don't have to spend our time on it.
