### ISSUE TITLE
Detroit - Affordable Housing 101 - How to find/apply

### ISSUE THREAD

**Issue by sheneral** [CityOfDetroit/bloom#1373]
As a resident
I want it to be easier to find the resources that tell me a more general overview of how affordable housing works
So that I can get an overview if I'm confused

**Acceptance Criteria**

- When I click on the Learn How You Can Find and Apply link below the Regions, then I will see the new Affordable Housing basics page with the videos
- When I click on one of the videos then I will see a modal that will show the video

**Notes**
* Add new homepage section learn how you can find and apply for affordable housing, that will take you to the Affordable Housing Basics page 
* Build a new Affordable Housing Basics page that will include 4 video cards that will open playback in a modal. The work to do that should be covered in the Core issue that will need to make its way back to Detroit 
* Remove the 4 videos from the current Resources page, I think they're the last ones 

**Designs**
https://www.figma.com/file/tUtgsJO8XnF9Ij2dwu22EF/bloom-public-general?node-id=2077%3A6866

QA Notes:
Start here https://detroit-public-dev.netlify.app/
1. After arriving at the homepage, scroll down to the action blocks
2. Ensure the new section described above is correct and the three sections are aligned
3. Click learn more
4. Test out the functionality of the media cards by clicking on the title or any part of the green header on the card
5. After viewing the video, ensure the modal can be closed
6. Test the same functionality on others cards

**Comment by kathyccheng** [comment]
LGTM
