### ISSUE TITLE
Long load times filter pt 2 

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1390]
Part of work in #1205 

Notes 
* update listings.service list to run the inner query to fetch the IDs and pass those into the main query, if there is no filter we can skip the inner filter query
* Could do in Core

**Comment by ludtkemorgan** [comment]
@YazeedLoonat Is this still applicable. Same for #1391

**Comment by YazeedLoonat** [comment]
closing!
