### ISSUE TITLE
[Bug] Incorrect Hover State on Filter Icon

### ISSUE THREAD

**Issue by ColinBuyck** [CityOfDetroit/bloom#1397]
This button is seen of the /filtered page and the hover state color for this svg should be white rather than green.
![Screen Shot 2022-07-19 at 11 45 59 AM](https://user-images.githubusercontent.com/53269332/179856011-b31ed01d-8477-4023-a9b4-1b65faabd0c6.png)

**Comment by kathyccheng** [comment]
LGTM
