### ISSUE TITLE
Detroit - Housing Basics Cleanup

### ISSUE THREAD

**Issue by ColinBuyck** [CityOfDetroit/bloom#1419]
1. Include updated links to the glossary and tutorial resources
2. Align media cards with info cards 

<img width="692" alt="image" src="https://user-images.githubusercontent.com/53269332/183725124-85313a2a-fda1-4383-adf8-8637271ce245.png">

**QA Notes**
Start here: https://detroit-public-dev.netlify.app/housing-basics
1. Verify that the media cards and info cards are aligned
2. Ensure that the new media card (bottom left) is functional by clicking the play button and seeing the modal appear
3. Verify that the updated strings and page layout reflects the linked sheet below.

**Comment by kathyccheng** [comment]
@ColinBuyck okay final copy + links is set here. We're gonna move the video resource up with the other ones, adjust the section description to remove mention of google.org, and don't worry about the the translation adjustment for now

https://docs.google.com/spreadsheets/d/1glJRJ6znXsYJwF2AAI0w6xhN59ebcEMO8Qr0JU2mLnU/edit#gid=197107808

**Comment by kathyccheng** [comment]
LGTM
