### ISSUE TITLE
Detroit: Add User Search + Sort 

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1421]
As an admin, 
I want to be able to search on the users table 
So that I can find someone specific 

**Acceptance Criteria**
* When I search by name, then it will filter the list
* When I search by listing name, it will filter the list
* When I search by email, it will filter the list 
* When I start typing, I'll see the 3 character min warning message 
* When hover over Name, Email, Listings, Role, Date Created, or Status, then I should be able to sort by then 

**Notes**
* Should already be done in Core, need to add into Detroit 
* Do we already have by listing search enabled?

**Comment by kathyccheng** [comment]
@ludtkemorgan I don't see this working on detroit dev yet. last time this happened, colin mentioned that he needed to rebuild the back end or something to get it to work. can you take a look? right now when I search, no results seem to get filtered.

**Comment by ludtkemorgan** [comment]
> @ludtkemorgan I don't see this working on detroit dev yet. last time this happened, colin mentioned that he needed to rebuild the back end or something to get it to work. can you take a look? right now when I search, no results seem to get filtered.

@kathyccheng I just manually deployed the backend and it is now working in dev. It is also working in production

**Comment by kathyccheng** [comment]
LGTM
