### ISSUE TITLE
[Bug] Unit Group Display Issues on Public

### ISSUE THREAD

**Issue by seanmalbert** [CityOfDetroit/bloom#1431]
STEPS TO REPRODUCE:
Go to the public site and view a listing like https://homeconnect.detroitmi.gov/listing/5ec672fb-37b1-4ff4-9427-53a5c7d4071a/the_village_of_university_meadows_4500_trumbull_detroit_mi

You'll see that AMI data is missing from the AMI column in the top unit group table.

You'll also see that the Household Maximum Income table is missing data.

EXPECTED RESULTS:
AMI data and Household Maximum Income data should display.

OBSERVED RESULTS:
![Screen Shot 2022-08-29 at 4 22 11 PM](https://user-images.githubusercontent.com/4401157/187315703-8cdeb26f-e03b-4ca5-ac19-ec1cd915180c.png)

**Comment by emilyjablonski** [comment]
QA Notes: 
Checkout a listing on dev that has AMI levels ([example](https://detroit-public-dev.netlify.app/listing/56256afd-1c63-462d-9b4b-0a1ffcf19e5c/clay_apartments_3300_mack_ave_detroit_mi))
And the same listing on this deploy preview (example)

**Comment by kathyccheng** [comment]
LGTM
