### ISSUE TITLE
Partners listings table not showing correct verified value

### ISSUE THREAD

**Issue by emilyjablonski** [CityOfDetroit/bloom#1450]
The partners listings table is not showing the correct `verified` value. The value appears to be correct on the listing obj because it is showing appropriately on the public site and the listing form, just not in the partners table.

**Comment by emilyjablonski** [comment]
QA Notes: Edit a listing to be verified and ensure the value shows correctly in the partners listing table.

**Comment by kathyccheng** [comment]
LGTM
