### ISSUE TITLE
Epic: Remove Applications

### ISSUE THREAD

**Issue by willrlin** [CityOfDetroit/bloom#146]
Tracking work for removing applications from the views

- [x] #156
- [x] #153
- [x] #157
- [x] #158
- [x] #159

**Comment by willrlin** [comment]
Assigning to @anders-schneider and @abbiefarr to continue creating tasks for this Epic.

**Comment by willrlin** [comment]
They have a "first come first serve" flag on the property; it's possible that we should just flag all the properties that way.

**Comment by avaleske** [comment]
For this work, are we putting it behind a feature flag or actually deleting the code?

**Comment by anders-schneider** [comment]
My memory is that every time we've talked about this, we've said we wanted to put it behind a feature flag. (I scoped #159 so that we wouldn't be deleting the Next code, just making it impossible for users to access the applications pages.)

**Comment by avaleske** [comment]
Ok cool, that's what I thought but I wanted to check.
