### ISSUE TITLE
Detroit - Listings Finder Translations + a few other missing ones 

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1460]
**Acceptance Criteria**
* Missing translations are added in Detroit 

**Copy** 
Copy of 822 tab 
https://docs.google.com/spreadsheets/d/1glJRJ6znXsYJwF2AAI0w6xhN59ebcEMO8Qr0JU2mLnU/edit#gid=1450753116

**QA Notes**
Start Here: https://deploy-preview-1453--detroit-public-dev.netlify.app/
Note: Due to the way the translations are set within the finder, the language must be selected prior to filling out the questions (requires a refresh if done midway through which clears answers).

1. Set the language on the homepage
2. Navigate through the listings finder to ensure that the translations are present
3. Then go to the housing basics page
4. Ensure the final three rows of the linked sheet are present here.

Additionally, the bottom three translations in the document are on the housing basics page.

**Comment by eajensenwa** [comment]
@ColinBuyck I think this is outside of the acceptance criteria for this issue, but do you know if we've documented this bug anywhere? "Finish" missing in Spanish translation
<img width="1202" alt="Screen Shot 2022-11-09 at 7 41 37 AM" src="https://user-images.githubusercontent.com/38386896/200952926-43c123ba-eea0-4b46-ac7c-f2b9a89f4678.png">

**Comment by eajensenwa** [comment]
@ColinBuyck LGTM - do you mind closing this one out for me? I still don't have permissions. Thx!
