### ISSUE TITLE
Unable to delete users in the partner portal

### ISSUE THREAD

**Issue by ludtkemorgan** [CityOfDetroit/bloom#1464]
[REMEMBER: a bug should be understandable years later by someone who will never talk to the reporter or assignee.]

STEPS TO REPRODUCE:
1. Open up any user in the partner portal and try to click the delete button.
2. After clicking the confirm delete an error occurs

ADDITIONAL INFORMATION:
It appears that this bug was addressed in core but never moved over to Detroit

**Comment by ludtkemorgan** [comment]
QA Notes:
- You should be able to open a user and delete it if you have the correct privilege.
- On deletion, the user should be deleted from user_accounts and corresponding tables. Also should be added to the activity_logs table

**Comment by ludtkemorgan** [comment]
This is now ready to be QAed again

**Comment by kathyccheng** [comment]
LGTM
