### ISSUE TITLE
Detroit: Incorrect Bordered Field UI with Arabic

### ISSUE THREAD

**Issue by ColinBuyck** [CityOfDetroit/bloom#1474]
The new bordered Field button UI breaks down in the right to left alignment used with Arabic.
<img width="828" alt="Screen Shot 2022-10-18 at 4 37 53 PM" src="https://user-images.githubusercontent.com/53269332/196564810-152787f2-cf6e-41ae-9836-c42804566348.png">
<img width="826" alt="Screen Shot 2022-10-18 at 4 38 01 PM" src="https://user-images.githubusercontent.com/53269332/196564813-ee97173c-ac0d-4f2f-83f3-1f00156a5fdd.png">

**Comment by emilyjablonski** [comment]
Related: #3149

**Comment by kathyccheng** [comment]
LGTM
