### ISSUE TITLE
Detroit Listing Finder: Spanish Homepage Stacks Hero Buttons

### ISSUE THREAD

**Issue by ColinBuyck** [CityOfDetroit/bloom#1477]
All other languages are horizontally-aligned with a gap and then at smaller screen sizes, they are vertically-aligned with a gap. This issue is likely due to the button text being longer but it should have spacing from the other button either way.
<img width="449" alt="Screen Shot 2022-10-21 at 4 08 10 PM" src="https://user-images.githubusercontent.com/53269332/197303515-011ca3e3-36cb-4d72-8313-10ad08fdf46c.png">

**Comment by eajensenwa** [comment]
@ColinBuyck LGTM

**Comment by eajensenwa** [comment]
@ColinBuyck could you also close this one out as well? Thank you
