### ISSUE TITLE
Detroit - Partners - Home Types

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1479]
As a leasing agent, 
I want to designate certain building types 
So that residents have a better understanding of the types of buildings they're moving into 

**Acceptance Criteria** 
* When I am in the listings tab in Partners Portal, then I will see a dropdown in the units section allowing me specify the type of building
* When I click that dropdown, I'll see the options - Apartment, Duplex, House, Townhome
* When I select one of those options and then click save, then I will see it in the listing summary on Partners 

**Notes**
* Add building type to listings model 
* Optional 
* Default: null 
* Options: Apartment, Duplex, House, Townhome
* No updates to the unit group 
* Each listing can only be one type 
* This includes setting all existing listings to Apartment type 

**Designs** 

Dropdown
https://www.figma.com/file/7mC6nLzTymt0pwxHGF7T6C/partners-typologioes?node-id=23%3A3077

Partners Summary
https://www.figma.com/file/7mC6nLzTymt0pwxHGF7T6C/partners-typologioes?node-id=23%3A3225

**Product Brief** 
https://docs.google.com/document/d/1Uh_FHRiiMbxZwpbvjd3Q8xhgX1x_2MhZn9gn8mblzJM/edit#

**QA Notes**
Start Here: https://detroit-partners-dev.netlify.app/sign-in
1. Log in into the partner's side
2. Select a listing
3. View the home type in the Listing Units section (ensure it matches figma)
4. Click edit
5. View the edit Listing Units section (ensure it matches figma)
6. Update the home type
7.  Ensure that the new information is reflected

**Comment by sarahlazarich** [comment]
QA'd this in staging - looks good to me!
