### ISSUE TITLE
Detroit - Public - Home Types Labels

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1480]
As a resident
I want to see what kind of building the listing is in 
So that I can make a better decision about what listing I'm interested in 

**Acceptance Criteria**
* When I am on the browse page, then I will see a label for building type in a different color than the accessibility features, first in the list, if a building type is added to the listing 
* When I am on a listing detail page, then I will see the same label for building type if one has been provided 

**Notes**
* Might need some clean up and updates to the labels to accomplish this 

**Designs** 

Browse 
https://www.figma.com/file/7mC6nLzTymt0pwxHGF7T6C/partners-typologioes?node-id=23%3A5927

Detail 
https://www.figma.com/file/7mC6nLzTymt0pwxHGF7T6C/partners-typologioes?node-id=23%3A3251

**Product Brief** 
https://docs.google.com/document/d/1Uh_FHRiiMbxZwpbvjd3Q8xhgX1x_2MhZn9gn8mblzJM/edit

**Comment by sarahlazarich** [comment]
QA'd in staging - looks good to me!
