### ISSUE TITLE
Detroit - Public - Add listing typology to filters 

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1482]
As a resident
I want to be able to filter by home types 
So that I can narrow down my search 

**Acceptance Criteria**
* When I open the filter, then I should see the Home Types option 
* When I choose one or multiple options, then I should see the options filter 

**Notes**
* The filter should be OR, so if the home type is one of the options OR one of the other options 

**Designs** 
https://www.figma.com/file/7mC6nLzTymt0pwxHGF7T6C/partners-typologioes?node-id=23%3A6088

**Product Brief** 
https://docs.google.com/document/d/1Uh_FHRiiMbxZwpbvjd3Q8xhgX1x_2MhZn9gn8mblzJM/edit

**QA Notes**
Start here: https://detroit-public-dev.netlify.app/listings
1. Open the filtering drawer
2. Experiment applying home type selections
3. Observe how the results change with each unique selection set (note there is only one duplex and one house seeded)
4. Further testing would involve updating home types on the partner's side and verifying that the updates are reflected in the filtered results.

**Comment by sarahlazarich** [comment]
Followed QA notes in staging, looks like this passed!
