### ISSUE TITLE
Detroit - General Copy Updates Public - Listing Typology

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1483]
As a resident, 
I want the content on the public side
To be encompassing of the different home types 

**Notes** 
* On the public side, where it says Management Company, it should say Contact Information 

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/3453407/199589758-102b036b-0978-4c62-8ce4-3ac98adc868d.png">

**Comment by sarahlazarich** [comment]
QA'd this in staging - looks good to me!
