### ISSUE TITLE
Detroit - Listing Finder Refactor to Include Updated Card

### ISSUE THREAD

**Issue by ColinBuyck** [CityOfDetroit/bloom#1486]
Listings Finder began prior to the completion of the Card component so it was not originally included, but this refactor will include it.

QA Notes:
Start Here https://detroit-public-dev.netlify.app/
1. Click Find Rentals for you
2. Click through the form and ensure its designs mirror the [Figma](https://www.figma.com/file/pIlN9vqLwUgOZYq6I5oM9l/bloom-public-eligibility-wizard?node-id=726%3A11522)
3. Resize the screen to mobile and ensure that it matches the QA notes left [here](https://github.com/CityOfDetroit/bloom/issues/1433#issuecomment-1299045427)

**Comment by kathyccheng** [comment]
LGTM
