### ISSUE TITLE
Detroit - Neighborhood Amenities Updated Fields 

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1488]
**Acceptance Criteria**
* When I'm in Partners Portal, the neighborhood amenity fields should be: Grocery Stores, Public Transportation, Schools, Parks and Community Centers, Pharmacies, Health Care Resources

**Notes**
* Sorry! there's been an update to the neighborhood amenity fields, we want to remove Senior Centers and add Parks and Community Centers and Public transportation. There's also some label updates. This is the final set: Grocery Stores, Public Transportation, Schools, Parks and Community Centers, Pharmacies, Health Care Resources
* This issue combines back end updates and front end updates

**Comment by emilyjablonski** [comment]
QA Notes: There are neighborhood amenities fields in create / edit listing, they will affect preview in partners, and will be displayed in public listing view, under the map

**Comment by kathyccheng** [comment]
LGTM
