### ISSUE TITLE
Detroit - Neighborhood Amenities Partners Bug 

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1489]
**Current Behavior**
* When I add in neighborhood amenities to the fields, and then I go and try to delete them, the listing will save but the content will re-appear and doesn't seem to be deleted
* If say, I add content in for multiple fields, and I delete one of them, that saves fine. But if it's the last field amongst the neighborhood amenities, then the content deletion won't persist. 

**Expected Behavior**
* When I add content to neighborhood amenities and then remove it, it should save and the content should be removed from the fields in Partners.

**Comment by emilyjablonski** [comment]
QA Notes
Remove existing neighborhood amenities from listing. They should be 'none' in partners listing preview, and should not be visible in public listing.

**Comment by kathyccheng** [comment]
LGTM
