### ISSUE TITLE
Detroit - Translations 

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1490]
Next round of translations 
https://docs.google.com/spreadsheets/d/1glJRJ6znXsYJwF2AAI0w6xhN59ebcEMO8Qr0JU2mLnU/edit#gid=1336041045

**Comment by sarahlazarich** [comment]
I see that there are translations listed in the Google Drive for the following phrases on the listing details page, but I'm not seeing them there in any language. Might need someone to point me the right way here! 
- Leasing Contact Information ("Contact Information" is listed in the sheet, and is translated) 
- Home Type (I see the square that shows the home type, but I don't see this phrase on the page) 
- Property Owner / Developer

**Comment by sarahlazarich** [comment]
Looked through several of the listings at https://detroit-public-dev.netlify.app/ 

The copy update was reflected, and the translations look good -- I think this is good to go! 

![image](https://user-images.githubusercontent.com/118844176/207162857-5fb53ceb-e0e8-4793-98f1-63896fdcc0a9.png)
