### ISSUE TITLE
Detroit: Missing Translations for Finder

### ISSUE THREAD

**Issue by ColinBuyck** [CityOfDetroit/bloom#1499]
Through development and QA, a few translations have been found to be missing. This issue is to fill in the [10/27 tab finder translations](https://docs.google.com/spreadsheets/d/1glJRJ6znXsYJwF2AAI0w6xhN59ebcEMO8Qr0JU2mLnU/edit#gid=1336041045) and "Finish" mentioned [here](https://github.com/CityOfDetroit/bloom/issues/1460#issuecomment-1309448618).

**QA Notes**
Start Here: https://detroit-public-dev.netlify.app
1. Select a language to test
2. Click through the finder to verify that those translations are present.
3. Go back to home page and select another language.
5. Repeat until all translations verified.

**Comment by kathyccheng** [comment]
LGTM
