### ISSUE TITLE
Filtering and pagination don't work together

### ISSUE THREAD

**Issue by anders-schneider** [CityOfDetroit/bloom#151]
Austin pointed out that http://localhost:3100/listings?page=1&limit=3&neighborhood=Foster+City should only return a single listing (with the Bloom seed data), but the pagination metadata is:

```
meta: {
  currentPage: 1,
  itemCount: 1,
  itemsPerPage: 3,
  totalItems: 7,
  totalPages: 3
}
```

`totalItems` and `totalPages` are incorrect; they should each be 1.

**Comment by avaleske** [comment]
This was fixed by #271, closing
