### ISSUE TITLE
Detroit - Missing Translations

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#1514]
As a jurisdiction
I want to regularly make sure I have all of the translations on my public portal as content is changing 
So that I can better serve non English speakers 

**Notes** 
* Run the missing translations script for Detroit 
* It should produce an excel format
* It may or may work in Detroit 

Given this is a script intended for internal use, I will update this with the final output when the PR has been approved.
[detroit-missing-translations.csv](https://github.com/CityOfDetroit/bloom/files/10290881/detroit-missing-translations.csv)

**Comment by sarahlazarich** [comment]
@ColinBuyck @kathyccheng can this be closed out? I was planning opening up new tickets with the results of my analysis, but happy to work in whatever format works best!

**Comment by kathyccheng** [comment]
Same let's close this out
