### ISSUE TITLE
Not all listings are showing additional eligibility section

### ISSUE THREAD

**Issue by emilyjablonski** [CityOfDetroit/bloom#1551]
We aren’t currently showing Credit History, Rental History, Criminal Background, or Building Selection Criteria on a medium amount of listings which do have data in those fields (it’s sort of weird, but it’s only showing those sections if the listing also has either programs or occupancy data - it shouldn’t be within that toggle, but it is).

We need to show the data in these fields if they exist.

QA Notes
Start Here: https://detroit-public-dev.netlify.app/
1. Locate a listing or create a listing without any occupancy data or program data.
2. Enter information on the partner's side for the following fields: Credit History, Rental History, Criminal Background, and Building Selection Criteria
3. Ensure the information still appears given the first condition (step 1) is true

**Comment by ColinBuyck** [comment]
I'm having a tough time reproducing this and specifically, am not seeing any issues with those sections on [Test Photos](https://detroit-public-dev.netlify.app/listing/6e0e4ffe-666f-477c-90ed-126766ab528e/test_photos) but could be missing a piece. Are you still seeing this behavior @emilyjablonski?

**Comment by emilyjablonski** [comment]
@ColinBuyck So sorry it looks like I included this fix in the PR where the matching components were removed in Detroit!

**Comment by ColinBuyck** [comment]
Oh no worries at all! I'll write up some QA notes and move it over 📦
