### ISSUE TITLE
Rental Finder - Min/Max rent input

### ISSUE THREAD

**Issue by sarahlazarich** [CityOfDetroit/bloom#1563]
**User Story**
As a…. Person using a screen reader inputting Minimum and Maximum rent on rental finder from the home page or from listings page 
I want…to input min/max rent using a text box with NO option for entering in increments
So that…I can input my minimum/maximum rent amounts, and scroll on the page without having the values I entered changed

**Additional detail:** 
Current experience allows a user to enter the min/max rent amount in text OR in increments of $1. However, when you scroll down on the page, the value you entered changes based on that scrolling. The proposed solution here is to make the min/max rent entry on both the rental finder from the home page and the listing page a text only input, eliminating the ability to enter in $1 increments, but fixing the scrolling bug. 

Design Asset Documentation:
Required (Y/N) N

Technical Notes Link: 
Change to UI components? (Y/N) N

**Acceptance criteria:**
Min/Max rent fields on rental finder (from home and listing page) are entered as a text field, and do not change when scrolling up or down on the page.

**Comment by ColinBuyck** [comment]
Related PR: https://github.com/bloom-housing/bloom/pull/3116/files

**Comment by ludtkemorgan** [comment]
@sarahlazarich this can be tested in https://detroit-public-dev.netlify.app/

**Comment by sarahlazarich** [comment]
lgtm!
