### ISSUE TITLE
Detroit Bash Frontend Bugs

### ISSUE THREAD

**Issue by emilyjablonski** [CityOfDetroit/bloom#1570]
(1) Text should not break in the header
(2) There should be more spacing between the information sections in the Leasing Agent section
(3) Favorite button size/alignment, should be right aligned and circular
![image (13).png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/4eca1a4a-aec4-4827-ac2a-511bbe1598de)
![image (12).png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/f765963b-df44-4586-9ea9-8b6aa1a65708)
![image (1).png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/f43bd74a-23ce-4c22-8edb-a905606edba6)

**Comment by emilyjablonski** [comment]
QA Notes:

For each of the three issues look at this [deploy preview](https://deploy-preview-1571--detroit-public-dev.netlify.app/) and ensure the issues are no longer present.

**Comment by sarahlazarich** [comment]
lgtm!
