### ISSUE TITLE
Gray background on page not found

### ISSUE THREAD

**Issue by emilyjablonski** [CityOfDetroit/bloom#1579]
There is a gray background behind the text on the page not found page in Detroit.

The background color of that section should be the same as the primary green color surrounding it.

![Screenshot 2023-03-13 at 1 40 15 PM](https://user-images.githubusercontent.com/65367387/224815004-13ae0740-5d7f-41ac-a42a-06b064104c27.png)

**Comment by sarahlazarich** [comment]
this was fixed by @ludtkemorgan
