### ISSUE TITLE
Bring upgrades over from Bloom Core

### ISSUE THREAD

**Issue by ludtkemorgan** [CityOfDetroit/bloom#1591]
We need to keep major upgrades in sync with core. The following needs to be upgrade

- Node 18
  - Our current version of node is outdated and we should update it to the latest.
  - This is a continuation of [#3317](https://github.com/bloom-housing/bloom/issues/3317).
  - Core commit: https://github.com/bloom-housing/bloom/pull/3343
  - Make sure to update Travis CI pipeline
- Next
- React

**Comment by ludtkemorgan** [comment]
This has been merged and can be tested in https://detroit-public-dev.netlify.app/.

Issues were found with the CSS that will most likely be fixed with https://github.com/bloom-housing/bloom/issues/3283

**Comment by sarahlazarich** [comment]
Issues found will be addressed by UIC alignment PR and can be QA'd as a part of that.
