### ISSUE TITLE
[Bug] Listing Export Issues

### ISSUE THREAD

**Issue by ColinBuyck** [CityOfDetroit/bloom#1595]
**Issue 1**: Column should be Developer/Property Owner rather than Developer Property Owner
**Reproduce** by clicking export to csv on the home page of the partners site

**Issue 2**: On the unit groups csv, ami charts have duplicates. 
**Reproduce** this by editing a listing to include a unit group with multiple ami levels using the same chart, then click export

**Issue 3**: On the listings csv, the leasing management company is not sucessfully pulling in the data
**Reproduce** by clicking export to csv on the home page of the partners site

**Issue 4**: On the listings csv, you can upload multiple paper applications in different languages but only one is showing in the paper app url field
**Reproduce** by upload multiple paper applications in different languages on a single listing, saving and then clicking export to csv on the home page of the partners site. nsure the listings csv correctly reflects the data

**Comment by sarahlazarich** [comment]
QA'd, lgtm.
