### ISSUE TITLE
[Bug] Memory Improvements to Listing Exports 

### ISSUE THREAD

**Issue by ColinBuyck** [CityOfDetroit/bloom#1602]
The formatting done in the listings-csv-exporter.service.ts demonstrates that significantly more data is being pulled in than is necessary for the export output. The clearest known example is in the use of addUnitSummariesToListings in. While it does provide needed formatting for rent ranges, it stores unneeded ranges of square footage, floor, and bathrooms. Additionally, it stores duplicate AMI chart names when only unique values are needed. This memory waste has the potential to create issues down the road as more listings are added to Detroit.

This ticket is to reduce memory usage in the listings export flow, starting with the use of addUnitSummariesToListings and then exploring other potential optimizations. Note: the addUnitSummariesToListings function is used in other contexts so if making direct changes to the function (as opposed to creating a new one), ensure there are no unintended impacts.

QA Notes: https://detroit-partners-dev.netlify.app/sign-in
1. Sign in
2. Click export to CSV
3. Ensure the data and particularly units data is still present, accurate, and formatted correctly

**Comment by sarahlazarich** [comment]
lgtm!

**Comment by sarahlazarich** [comment]
lgtm!
