### ISSUE TITLE
[Bug] User's Last Logged In Not Updating

### ISSUE THREAD

**Issue by ColinBuyck** [CityOfDetroit/bloom#1610]
On Detroit, the Last Logged In field (the last column of the User export) is not updating. Logging into prod or dev under any account and then exporting will show an outdated last logged in date and time. For example, the dev account [here](https://detroit-partners-dev.netlify.app/users) shows 04-14-2022 12:23AM for Last Logged in.

QA: https://detroit-partners-dev.netlify.app/sign-in
1. Sign in to the partners site with admin@example.com
2. Download the user export
3. Verify that the admin user has a recent last logged in time.
Note! This won't retroactively fix the data since this fix allows it to be stored. Other users will show outdated times until they log in again.

**Comment by sarahlazarich** [comment]
Looks good!
