### ISSUE TITLE
Investigate redis usage in Detroit

### ISSUE THREAD

**Issue by ludtkemorgan** [CityOfDetroit/bloom#1619]
We removed all usages of redis from core, however it still exists in Detroit. It is being used by a throttling system as well as queueing services (e.g listings-notifications.ts). 

One reason we removed redis was because it wasn't working as intended in heroku for core. We should investigate to make sure that the redis functionality is actually working as intended and if migrating off of it is a better option.

The outcome of this ticket should determine what to do with redis in Detroit.

**Comment by ludtkemorgan** [comment]
Update on this ticket:
- Our redis version in Detroit will no longer be supported later this year:
```
We urge you to upgrade to version 7.2 as we’re disallowing provisioning of the deprecated version from 02 Oct, 2024. If no action is taken, then we’ll perform forced upgrades after 31 Oct, 2024.
```
- Because of this it has become a higher priority to address this ticket. Ideally we should be able to remove Redis with a small amount of code changes, but some investigation is needed.

@sarahlazarich fyi

**Comment by sarahlazarich** [comment]
See if this is being used, and if it isn't, remove it 
If it's being used, upgrade

**Comment by ludtkemorgan** [comment]
The redis removal has been completed in the dev environment https://detroit-partners-dev.netlify.app/ and https://detroit-public-dev.netlify.app/
the app is running as expected

**Comment by ludtkemorgan** [comment]
This has been deployed to staging and redis instance has been removed. Note: there is no DB associated to this environment so the app is not accessible.
