### ISSUE TITLE
Hover state on the "resend email confirmation" button is white

### ISSUE THREAD

**Issue by emilyjablonski** [CityOfDetroit/bloom#1623]
![Screenshot 2023-05-12 at 3.12.56 PM.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/a37eefa2-dfff-4f42-a348-8ad06e493d73)

Hard to see from this screenshot, but there is a second button to the left that is invisible on hover

**Comment by ludtkemorgan** [comment]
This has been fixed: 
![image](https://github.com/CityOfDetroit/bloom/assets/42942267/33f93b62-0807-494d-9294-30184fdedb44)
