### ISSUE TITLE
[Bug] Errors not highlighting fields in Detroit

### ISSUE THREAD

**Issue by ColinBuyck** [CityOfDetroit/bloom#1625]
We seem to have recently introduced the error highlighting issue when adding a new listing on partners. The discrepancy can be seen in the two screenshots below:
Dev:
<img width="1094" alt="Screenshot 2023-05-16 at 11 12 40 PM" src="https://github.com/CityOfDetroit/bloom/assets/53269332/9eabfd26-85f4-4b42-989b-bc5eeb1d34fb">

Prod:
<img width="1310" alt="Screenshot 2023-05-16 at 11 12 30 PM" src="https://github.com/CityOfDetroit/bloom/assets/53269332/ae3c3e3a-0d22-4470-a05a-04cac4114dee">

Related: https://github.com/bloom-housing/bloom/pull/3448

**Comment by sarahlazarich** [comment]
This is fixed in Core, needs to be addressed in Detroit

**Comment by KrissDrawing** [comment]
QA Notes: on https://detroit-partners-dev.netlify.app/ 
publish listing without name and fill just `street Address` for building details without rest address fields.

**Comment by sarahlazarich** [comment]
looks good!
