### ISSUE TITLE
Min and Max rent filter fail if there are at least 4 digits

### ISSUE THREAD

**Issue by ludtkemorgan** [CityOfDetroit/bloom#1632]
STEPS TO REPRODUCE:
1. Go to the Detroit listings page and click on the filters
2. Add at least a 4 digit number into either the Min or Max rent fields. (e.g 1000)
3. No results will appear and an error shows on the backend
`filter.1.maxRent must be a number string`

This is happening most likely because the front-end adds a comma after entering it and sends that to the backend. Also it appears to have started after the Aug 1st release

**Comment by KrissDrawing** [comment]
QA notes: on https://detroit-public-dev.netlify.app/listings click `find rentals for you` now filtering by numbers bigger that 1000 will send proper value (without comma), so it will filter as expected.
Should also work for: https://detroit-public-dev.netlify.app/listings/filtered and https://detroit-public-dev.netlify.app/finder filtering

**Comment by sarahlazarich** [comment]
lgtm!
