### ISSUE TITLE
Filtering by Min/Max seems to be flipped

### ISSUE THREAD

**Issue by ColinBuyck** [CityOfDetroit/bloom#1633]
The video below demonstrates how increasing the minimum rent results in a greater amount of search results and the opposite occurs when decreasing the max rent. It seems these fields are reversed in some way.
https://github.com/CityOfDetroit/bloom/assets/53269332/d3109ff6-7bc1-4a8c-88bb-319c496a1873

**Comment by KrissDrawing** [comment]
QA Notes: on https://detroit-public-dev.netlify.app/listings click `find rentals for you` now min/max rent values should show proper values. So setting 0 in min rent should show every listing with units. Its not working with more complex values like span, percent, so it will only filter flat values. Also should work properly when setting in https://detroit-public-dev.netlify.app/finder

**Comment by sarahlazarich** [comment]
lgtm!
