### ISSUE TITLE
Error when Resetting Partners Password

### ISSUE THREAD

**Issue by iph-97** [CityOfDetroit/bloom#1640]
Our jurisdictional partner in Detroit tried to reset their password and was unable to do so. They received the reset email, but an error was thrown up once they tried to submit their new password. I was able to replicate the issue and received the same error message. This is a medium priority issue. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0xTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5a40dfcb3bc402e9ccd2ac28982129dbed7e71f8/image.png)

**Comment by YazeedLoonat** [comment]
This is an issue seemingly only on detroit

seems like its caused by TypeORM using too long of a column alias during the actual querying of the DB. Which is causing issues later down the line in TypeORM once it gets a response from the DB

**Comment by sarahlazarich** [comment]
@YazeedLoonat is there anything to be done about this now or are we waiting for the Prisma swap to hopefully fix?
