### ISSUE TITLE
Det: URL Directing to Arabic Home Page

### ISSUE THREAD

**Issue by iph-97** [CityOfDetroit/bloom#1652]
Safiya noticed that when you navigate to homeconnect.detroitmi.gov it takes you to the Arabic landing page. Can we put English back as the default? Also, why did this switch? I was able to replicate the issue. This is a medium priority issue :large_yellow_circle:. 

"When I put in the website name for Home Connect, it automatically goes to the Arabic version? Do you know what is happening?"

**Comment by sarahlazarich** [comment]
fixed
