### ISSUE TITLE
Remove /listings request from homepage

### ISSUE THREAD

**Issue by avaleske** [CityOfDetroit/bloom#179]
The homepage makes a request to /listings for data about how many listings are open. That seems unnecessary and like it might slow the site down, so we should consider removing it.

The data call:
https://github.com/CityOfDetroit/bloom/blob/e31feb5880a40ebecd64e3c841871e065ed3780c/sites/public/pages/index.tsx#L85-L85

**Comment by avaleske** [comment]
@willrlin I wasn't sure which epic to use for this.

**Comment by willrlin** [comment]
We could create a new one, something that captures anything for "adapting to Detroit"? Content seems fine for now.

**Comment by willrlin** [comment]
Or a performance epic.
