### ISSUE TITLE
Decide whether to surface per-unit information in the listing view

### ISSUE THREAD

**Issue by anders-schneider** [CityOfDetroit/bloom#181]
[`UnitTables`](https://github.com/CityOfDetroit/bloom/blob/main/ui-components/src/page_components/listing/UnitTables.tsx) is a React component that we use in the Listing view, and it can show per-unit information:

![image](https://user-images.githubusercontent.com/8754454/125469562-4f81f29f-ab57-4332-b576-2ce86dd06643.png)

Do we want that? Based on recent conversations, I don't think we want to surface any data at the level of an individual unit (we only want to surface summarized data about units).

If we decide *not* to surface per-unit information:
- The simplest thing to do is set [`disableUnitsAccordion`](https://github.com/CityOfDetroit/bloom/blob/12b855a9947b2a61c0a9cadee2d0a45aaf81ead5/backend/core/src/listings/entities/listing.entity.ts#L249) on every listing, which just marks the per-unit-info table as "hidden"
- Alternatively, we could refactor `UnitTables` to not include the full table of per-row info (and maybe rename it to `UnitSummaries` or something like that)

If we do decide to surface per-unit information:
- The current headers for the table are unit number (e.g. 101A), square feet, number of bathrooms, and what floor the unit is on. We should remove the ones of those we don't have good data for, and maybe add other fields that we do have data for (e.g. availability/vacancy).

**Comment by willrlin** [comment]
We've decided at this point to only show summaries.
