### ISSUE TITLE
Ideate on the availability update flow

### ISSUE THREAD

**Issue by willrlin** [CityOfDetroit/bloom#200]
Work with Tom and Gabe and property manager group to come up with options for how property managers might update availability.

Some options we've already discussed:
- email updates with "click to update availability"
- CSV import from property manager software with unit level availability info
- property manager login to partner portal and edit the availability in the unit summary field

**Comment by abbiefarr** [comment]
HRD is keen to have email reminders to edit availability, and in a recent meeting brought up two possibilities:
1) Including in the email a link to the portal where they can update availability
2) Allowing PMs to update availability from within the email, like an embedded form.

I have hesitations about #2 for security reasons. I think a login should really be required to edit availability data. Plus it's more engineering time than a simple reminder with a link, and for not much gain, given that either way they're still filling out a form.

**Comment by abbiefarr** [comment]
Safiya also mentioned that getting any CSVs from PMs might be a problem, and if we get them they're unlikely to be in a workable format, and may be inaccurate. Currently, her preferred workflow seems to be to seed the database with some initial data, and after that PMs are exclusively editing the availability summary table.

Initial data exists in a sheet already, and additional data is being gathered now via Google form. It includes information about the property (amenities, accessibility features, etc), and a summary of availability. Data on individual units is not being collected AFAIK. 

So IMO this is what we'll need:
1) A new table for availability summaries
2) A way to import initial data (including the availability summary) via CSV, potentially from two separate CSVs. Note that the summary table would be populated directly, and not derived from data on individual units
3) Ability for PMs to update availability summaries directly from the portal

**Comment by abbiefarr** [comment]
And the flow for PMs looks like:
1) Receive an email reminder to refresh availability data with link to do so
2) Click link, navigate to login
3) Login, automatically directed to the edit availability form
4) Update form and submit

**Comment by abbiefarr** [comment]
Tickets for initial work have been filed. Closing this for now.
