### ISSUE TITLE
Scope the first few CSV import tasks

### ISSUE THREAD

**Issue by willrlin** [CityOfDetroit/bloom#203]
Done here means scoping out how much work it would be to build some kind of UI for importing CSVs. See comments on the CSV epic for more information.

We should also consider if any NPM packages exist that can do this.

**Comment by anders-schneider** [comment]
From Kar's email: "We have deprioritized bulk upload / edit options via HRD admin portal due to time constraints". I'll unassign and move this out of the current milestone and sprint.

**Comment by willrlin** [comment]
Closing this since we're not going to do it.
