### ISSUE TITLE
Update querystring format so param ordering doesn't matter

### ISSUE THREAD

**Issue by avaleske** [CityOfDetroit/bloom#210]
Blocked by question to Sean.

Right now, the filtering querystring is brittle. The backend breaks if we pass urls like `/listings?filter[$comparison]=>&filter[depositMin]=500&filter[$comparison]=<>&filter[name]=Coliseum&filter[$comparison]=<&filter[depositMin]=900
` because fields with the same name get grouped into an array, so the resulting filter object is
```
{$comparison: ['>', '<>', '<'], depositMin: ['500', '900'], name: 'Coliseum'}
```
which will not be iterated over the same way the comparisons were specified.

Additionally, if the `$comparison` param is not specified first, addFilter() breaks entirely.

Sean mentions [here](https://github.com/bloom-housing/bloom/discussions/1400#discussioncomment-1010385) that they're open to changing the query string format, and adds some ideas on how we might do that.

Ideally, it's to something that let's us pair a field with a comparison type directly, instead trying to do so by keeping params in a certain order.

**Comment by willrlin** [comment]
@seanmalbert said there was some work being done to clean up filtering; I think it's possible that fixes this issue as well.

**Comment by willrlin** [comment]
I think this is fixed now by the upstream merge. @avaleske, reopen if not.
