### ISSUE TITLE
Unblock the ability to have multiple photos per listing (backend work)

### ISSUE THREAD

**Issue by anders-schneider** [CityOfDetroit/bloom#212]
Exygy has WIP to support photo upload through the partner portal ([Q&A question on this](https://github.com/bloom-housing/bloom/discussions/1400#discussioncomment-1010632)). Once that lands, it'll be limited to one photo per listing (this was just an oversight, not a design decision). They've created https://github.com/bloom-housing/bloom/issues/1530 and, if having multiple photos per listing is a high priority for us, invited us to send a PR for that. Creating an issue on our side to keep track of this.

**Comment by ludtkemorgan** [comment]
Completed work
