### ISSUE TITLE
Gracefully handle missing availability+waitlist data

### ISSUE THREAD

**Issue by avaleske** [CityOfDetroit/bloom#230]
We need the listings view to gracefully handle missing availability data. See #228 for the strategy for this, which could be either a simple "Unknown" or a prompt to contact the property manager.

Per the PRD:
Workflow for No Data: Contact Property via phone/email solution for no data / limited data sets (including accessibility)

**Comment by willrlin** [comment]
We already hide the waitlist data if there is no waitlist information; I think for the missing availability information that should be handled in #229
