### ISSUE TITLE
[Eligibility Questionnaire] Check property websites for requirements

### ISSUE THREAD

**Issue by elenm** [CityOfDetroit/bloom#236]
We need to do research to understand what kind of restrictions and requirements different properties have to ensure we are asking the correct questions in the eligibility questionnaire.

**Comment by willrlin** [comment]
@tomgebauer @ChelseaRucker can we get a 20%er or other non-SWE to figure out the content for the eligibility questions and make sure we're not missing anything?

**Comment by elenm** [comment]
Here is some more information on affordable housing eligibility: 
* [Detroit eligibility guidelines](https://detroitmi.gov/departments/housing-and-revitalization-department/affordable-housing/who-eligible)
* [Detroit 2020 income and rent limits](https://detroitmi.gov/sites/detroitmi.localhost/files/2020-08/2020%20Income%20Limits.pdf)
* [HUD public housing eligibility information](https://www.hud.gov/topics/rental_assistance/phprog) -- are these properties considered public housing?

Some conclusions I'm drawing from this: 
* We need to ask how many people will be living in the property instead of how many bedrooms they need. This is because, the number of people factors into the AMI calculation.
* We may be able to surface rent information because it seems that rent is determined by tenant's income rather than set by the property (see the rent limits section in the second document)
* We may need to build a feature for HRD to update the AMI and multipliers on an annual bases into the HRD admin portal, because these will likely change.

I still have a number of questions, so I'm going to start a doc with them.

**Comment by willrlin** [comment]
I opened #462 for the possible feature of showing estimated/calculated rents. The other conclusions are covered in #447 and #449 among others. I checked other property management company websites and couldn't find other easy eligibility questions to ask that wouldn't involve getting data that the company needs to see in person anyway (like documents).
