### ISSUE TITLE
[Eligibility Questionnaire][Accessibility] Focus shifted to top of page when navigating between pages 

### ISSUE THREAD

**Issue by elenm** [CityOfDetroit/bloom#267]
Focus is shifted to the top of the page when navigating between eligibility questionnaire pages (consider whether we should shift focus to the page heading).

**Comment by avaleske** [comment]
I looked through https://www.w3.org/WAI/tutorials/forms/multi-page/ and didn't see anything about moving focus to the form on multi-page forms (beyond the normal "skip to main content" link) but I think adding a "current page" screen-ready only text as it reads through the progress bar would be helpful.

**Comment by avaleske** [comment]
Changes for this are in https://github.com/CityOfDetroit/bloom/pull/660
