### ISSUE TITLE
[Translations] Set up initial translations

### ISSUE THREAD

**Issue by elenm** [CityOfDetroit/bloom#277]
Set up initial translations (even if they're not human generated yet).

**Comment by willrlin** [comment]
What are you planning to do regarding the initial translations? Should we just send a JSON file with the strings we have currently to get translated? I don't want to get into a situation where we don't know which strings we've gotten translated by humans and which we've auto-generated somehow and would have to figure out which ones need new translations or updates.

**Comment by elenm** [comment]
The [translations are not showing up in the UI](https://user-images.githubusercontent.com/16543000/128066126-6de9b190-8208-42f6-8885-e8e455e08133.png) in our demo production deployment. 

I updated the sites/public .env file to include the required languages, but I think the LANGUAGES environment variable is not being loaded at all and we are [defaulting to the "English" locale](https://github.com/CityOfDetroit/bloom/blob/6a00e71dfa36312a9cc51009d22108854dc4373d/sites/public/next.config.js#L56) only. 

I'm trying to figure out why this is happening.

**Comment by willrlin** [comment]
I think this is another case of build time vs. run time environment variables. NextJS generates the pages at build time, where the environment variable is not defined, so it defaults to just "en". You'll need to update the Dockerfile to define that variable as an ARG.

**Comment by elenm** [comment]
Thank you Will!
