### ISSUE TITLE
[Unit Summary] Map embedded

### ISSUE THREAD

**Issue by kar-r-green** [CityOfDetroit/bloom#291]
Map location embedded in unit summary details page

**Comment by willrlin** [comment]
Is this something different than what's already existing in the listings detail page?

**Comment by kar-r-green** [comment]
nope, it's the same thing - didn't know if we needed extra build on top of Bloom. If not, let's delete. thanks!

**Comment by willrlin** [comment]
I think we're all set then for this one, thanks! We can open a separate one for StreetView integration.

**Comment by kar-r-green** [comment]
@willrlin quick clarification: is there an embedded / interactive map option for the listings page or is 'View on Map' the solution?

checking with you first on status before to opening a requirement for Q4 given user feedback or an interactive map embedded in the listing details. thanks!

**Comment by willrlin** [comment]
#129 tracks integrating Detroit's mapping API into the deployed site to show up on the listing details page.

On the "all listings" page, map integration would be #290. And the street view is #428. Hope that clarifies!

**Comment by kar-r-green** [comment]
Thanks, appreciate the clarification!
