### ISSUE TITLE
No housing counselors

### ISSUE THREAD

**Issue by willrlin** [CityOfDetroit/bloom#301]
The HOUSING_COUNSELOR_SERVICE_URL env variable points to a JSON file that will populate the `housing-counselors.tsx` page. See https://housing.sfgov.org/housing-counselors for an example of what this looks like. [Alameda County](https://housing.acgov.org/) instead just redirects the `Get Assistance` link in the upper right to `https://www.acgov.org/cda/hcd/index.htm`.

We should decide what we want to do with that page, whether to try to get a json file or just to point it elsewhere.

**Comment by willrlin** [comment]
It looks like in the mocks the "Get Assistance" is a separate entry on the front page only that will link to something - @kar-r-green @tomgebauer to confirm what that link (shown as "CTA" in the mocks) will go to.

**Comment by tomgebauer** [comment]
This is meant to link to a site section like [this](https://housing.acgov.org/additional-resources), but the content for this is currently unknown. @ChelseaRucker unsure if this is something we want to try to resolve in our content working session. If we can't resolve this for MVP launch then we should remove it from the front page.

**Comment by willrlin** [comment]
Gotcha, so I understood from your comment that we are NOT going to have a housing counselor page like [this](https://housing.sfgov.org/housing-counselors). The help page you linked is tracked separately (#281 to start, and @ChelseaRucker is working on that). Closing this since we won't have housing counselor specific page.
