### ISSUE TITLE
Add ADA Features Filter

### ISSUE THREAD

**Issue by avaleske** [CityOfDetroit/bloom#320]
Add filtering based on ADA accessibility features, on the building or on the listing. See #609 for the fields added to the database.

Some notes:
- We only have data on the building, not the specific unit, so that will need to be reflected in the frontend filter (see #591)
- Should the filter be a checkbox, or dropdown that lets you select "some units in building have features" or "all units in building have features"?

**Comment by jnowell** [comment]
Design for this is viewable in [Figma](https://www.figma.com/file/wAhoXVmHRIJ2TyBKFVq2JY/Desktop-and-Mobile-Experiences?node-id=3540%3A13497) (02.2). Only caveat is that it should read 'Laundry in building', not 'Laundry in unit'.
