### ISSUE TITLE
Zip Code Filter

### ISSUE THREAD

**Issue by avaleske** [CityOfDetroit/bloom#321]
Add filtering by zip code (and multiple zip codes?)

This will need:
- #255 
- A UI Component to add multiple things to a text field

**Comment by willrlin** [comment]
The current mocks show a text field, so I'm going to first just use a simple comma separate list where the user would just enter everything. We can talk about adding a better component that validates and separates the values later.

![screenshot](https://user-images.githubusercontent.com/4317058/129239225-d1ef8104-14cf-4f07-a7ea-04e050e6c18c.png)

**Comment by avaleske** [comment]
Thanks for taking this!
