### ISSUE TITLE
Move "Contact Leasing Agent" section up

### ISSUE THREAD

**Issue by anders-schneider** [CityOfDetroit/bloom#328]
![image](https://user-images.githubusercontent.com/8754454/128242269-61d923b0-41cf-4849-b923-317b6f97a785.png)

This gets us closer to what Kar is proposing in https://github.com/CityOfDetroit/bloom/issues/207#issuecomment-892905541

**Comment by pfeeny5** [comment]
This one seems similar to #348. That one removes the extra blocks from the right hand side, vs just moving the location of them up.

**Comment by willrlin** [comment]
Ok sounds good, thanks. Closing this as a duplicate.
