### ISSUE TITLE
Remove empty bar beneath listing photos in "all listings" view

### ISSUE THREAD

**Issue by anders-schneider** [CityOfDetroit/bloom#332]
![image](https://user-images.githubusercontent.com/8754454/128249395-e61cbd85-d4b6-4ac0-910a-1cd481c5f702.png)

**Comment by willrlin** [comment]
This is only with Detroit data, right? Maybe this will be covered by Patrick's work in #157?

**Comment by anders-schneider** [comment]
Ah right, this looks like a dupe, thanks!
