### ISSUE TITLE
Run migrations on deployed database

### ISSUE THREAD

**Issue by anders-schneider** [CityOfDetroit/bloom#335]
And maybe record/publish notes if they don't already exist?

I'll wait until #325 is merged before doing this.

**Comment by willrlin** [comment]
I have notes in the wiki about connecting directly to the deployed database, but for this task it should literally be:
* setup `.env` file (I'll give you the keys you need)
* run the script

**Comment by willrlin** [comment]
To verify, you'll need to look at Pantheon to see that backend-core correctly deploys.

**Comment by anders-schneider** [comment]
Did this. A couple quick notes:
- Instructions for connecting to our Cloud SQL instance are here: https://github.com/CityOfDetroit/bloom/wiki/Deployment#connecting-to-the-deployed-cloudsql-instance
- I didn't understand what Cloud SQL Auth proxy was doing (and maybe still don't). My best understanding: it does port-forwarding between my local machine and the Cloud SQL instance, so that when I run a command locally that talks to port 5432 (where the local postgresql database server runs), it actually talks to the deployed Cloud SQL database server.
- I just set temporary environment variables based on what Will sent me (`export PGUSER=...`)
- I first ran `yarn typeorm migration:show` to see how many migrations there were to run
- Then I ran `yarn db:migration:run` to apply the migrations
- Then `yarn typeorm migration:show` again to show that the migrations were indeed completed.
- Lastly, checked GCP console to see that backend-core was successfully deployed:

![image](https://user-images.githubusercontent.com/8754454/128412004-94b477bd-fd4d-4db8-9372-9b1edfc29d70.png)

I'll keep this ticket open so that I remember to write a more polished version of this in the wiki

**Comment by anders-schneider** [comment]
I also went to {backend-core-url}/docs and checked that the fields added by the migrations were indeed in the Swagger UI

**Comment by willrlin** [comment]
Oh you didn't run the script I created for this?

**Comment by willrlin** [comment]
In the future it should be enough to setup `bin/.env` with the variables and then run `bin/run_prod_database_migration.sh`.

**Comment by anders-schneider** [comment]
Haha whoops, I now see your script 🙃 

And it looks like you've updated the wiki, thanks!
