### ISSUE TITLE
[Bug] Units view selector doesn't auto populate in partner view

### ISSUE THREAD

**Issue by abbiefarr** [CityOfDetroit/bloom#336]
STEPS TO REPRODUCE:
1. open the partner portal and edit a listing

EXPECTED RESULTS:
In the Units Info section, one of the radio buttons should be auto selected based on which preference is currently set.

OBSERVED RESULTS:
No radio buttons are selected.

ADDITIONAL INFORMATION:
Happened after this [merge from upstream](https://github.com/CityOfDetroit/bloom/pull/325).

**Comment by willrlin** [comment]
Do we know that this doesn't happen on bloom? I think it's not worth fixing at the moment. Pushing to a later milestone.
