### ISSUE TITLE
Update summary table on individual listing page

### ISSUE THREAD

**Issue by pfeeny5** [CityOfDetroit/bloom#347]
Update the unit summary table to reflect mock up columns (and available data)

![image](https://user-images.githubusercontent.com/82653098/128412105-e7aaf187-29c3-4994-8c74-1540ca758b80.png)

**Comment by anders-schneider** [comment]
Recording what I remember from conversation with Tom: we want this table to have three columns ("Unit Type", "Availability", and "Total Count"). For now, the "Availability" column will only have "waitlist" (or whatever placeholder text we want), but we'll be able to replace that with the available count once we have that data.

**Comment by anders-schneider** [comment]
We no longer have this table at all in our `ListingView`. The reason: `amiValues` (populated here: https://github.com/CityOfDetroit/bloom/blob/13adcbb7a7c033e93b43cddc24c66c46eaf42f54/sites/public/src/ListingView.tsx#L52) is empty and that makes it so we don't create a `GroupedTableGroup` of unit types.

**Comment by anders-schneider** [comment]
I'm confirming that we do still want this table to appear. Assuming that's true, I believe this should read from the new `Listing.unitsSummary` instead of the derived `Listing.unitsSummarized`.

**Comment by anders-schneider** [comment]
Blocked by #345
