### ISSUE TITLE
Remove Eligibility section from Listing details view

### ISSUE THREAD

**Issue by pfeeny5** [CityOfDetroit/bloom#349]
Remove the Eligibility section from a listing's details view.

![image](https://user-images.githubusercontent.com/82653098/128412370-35b900d5-6ee6-43ce-b9dd-f128628d19a8.png)

**Comment by willrlin** [comment]
@tomgebauer - this is also the place in the UI where they call out the maximum income - we might end up getting some portion of that data, will you be designing some other way to display some of this eligibility information?

**Comment by willrlin** [comment]
See https://sites-public-tj3gg4i5eq-uc.a.run.app/listing/ee0d8211-23a3-447d-9ade-83863f840c90/test_default_reserved_548_market_street_san_francisco_ca for instance.

**Comment by willrlin** [comment]
I'm just removing it all for now; we can decide if we want to add some portion of it back in later.
