### ISSUE TITLE
[Bug] Button disappears on mouse-over

### ISSUE THREAD

**Issue by willrlin** [CityOfDetroit/bloom#361]
STEPS TO REPRODUCE:
1. Go to front page
2. mouse over the "browse rentals" button

EXPECTED RESULTS:
The button should probably still be visible as a button.

OBSERVED RESULTS:
It blends in with the surrounding color.

ADDITIONAL INFORMATION:

![DBz9SyUmykhJcJA](https://user-images.githubusercontent.com/4317058/128739343-fad7a888-be2c-4f1b-bc56-995169299cf5.png)

**Comment by willrlin** [comment]
The mocks don't have mouse-over views; @tomgebauer for thoughts on this bug.

**Comment by jnowell** [comment]
This is obsolete in light of recent design.
