### ISSUE TITLE
Add validation to $comparison Filter param

### ISSUE THREAD

**Issue by avaleske** [CityOfDetroit/bloom#365]
In https://github.com/CityOfDetroit/bloom/pull/356 we ensure that the value of $comparison is valid before we use it in the query, but it would also be good to ensure that param itself is validated, by adding validation to the BaseFilter params here:
https://github.com/CityOfDetroit/bloom/blob/88b7afba94283901194bf9c66471c70559bfa61f/backend/core/src/shared/dto/filter.dto.ts#L10-L18

This will require getting validation working for the ListingFilterParams field of ListingQueryParams.

Decorators that could be useful include:
- `@IsInstance` - makes sure it’s an instance of a class
- `@ValidateNested` - validates sub classes
- `@Type` - converts a plain object to a class

**Comment by willrlin** [comment]
@avaleske - did Exygy already cover this by the upstream filter changes or is there more validation necessary here?

**Comment by avaleske** [comment]
Exygy already already covered this, yeah.
