### ISSUE TITLE
fix backend/core tests

### ISSUE THREAD

**Issue by willrlin** [CityOfDetroit/bloom#369]
backend/core e2e tests started failing with `error: database "bloom" does not exist`. They seem to be flaky and will sometimes pass, but even while passing, they still contain errors.

**Comment by willrlin** [comment]
I was able to consistently reproduce the failure locally by dropping the bloom database and running the tests. They pass at commit 1a560936 (Add M12 automation) but fail at commit 49bb6aaa (Merge pull request #358).

**Comment by willrlin** [comment]
@avaleske I checked #358 again but couldn't find anything that would point to the `listing.e2e-spec.ts` start looking at the `bloom` database instead of `bloom_test`. Do you have any ideas?

**Comment by willrlin** [comment]
Ah, I figured it out - apparently, calling `getSeedListingsCount()` and importing it from the seeder attempts to actually seed the database. I'll send a PR soon to remove that.

**Comment by avaleske** [comment]
Is there a way to still get the count of seeds without trying to seed the database? Moving it to a different module or something?

**Comment by willrlin** [comment]
Can we just get the total listings with a separate call to /listings?

**Comment by avaleske** [comment]
Hmmm since the code under test is the /listings endpoint, I'd want to have
a different way of getting the expected number of results.

**Comment by willrlin** [comment]
Added a comment and hard coded it in #373. I opened #374 to track the future improvement.
