### ISSUE TITLE
CSV import for data collected from property manager survey

### ISSUE THREAD

**Issue by anders-schneider** [CityOfDetroit/bloom#395]
I just chatted with Gabe, and we've started to receive responses to the property manager survey! This data lives in a spreadsheet that we can export as a CSV.

I see two possible approaches to get this data into our DB:
1) Write a separate CSV import script to ingest the newly collected data. This script would look up existing listings by HRDID, and then add the additional data (without touching the fields populated by the other CSV import script, #227).
2) Join the new spreadsheet with the pre-existing HRD spreadsheet (ie add a bunch of new columns to that spreadsheet). Then make changes to the existing CSV import script to interpret+ingest the new fields.

Done criteria: we have a way to ingest the data from the property manager survey (and any manual steps that are needed before running a script are documented).

**Comment by anders-schneider** [comment]
Mapping of (question in survey) --> (where the data should live in the data model) is here: https://github.com/CityOfDetroit/bloom/issues/396#issuecomment-909624118

**Comment by willrlin** [comment]
FYI there are some updated on #396 that would affect the listing imports.

**Comment by anders-schneider** [comment]
This has been superseded by #567, which has more detail (maybe I should remember what tickets I create and/or check before creating a whole new ticket for something that already exists 🤦 )
