### ISSUE TITLE
Map property manager survey fields to data model fields

### ISSUE THREAD

**Issue by anders-schneider** [CityOfDetroit/bloom#396]
Done criteria: create a mapping between all of the fields in the property manager survey and how they correspond to fields in the data model. In particular, flag instances where a new field is needed in the data model.

**Comment by willrlin** [comment]
@anders-schneider were you already tracking this somewhere? I think we've arrived at a pretty good consensus around how to map the data onto our data model.

**Comment by anders-schneider** [comment]
https://github.com/CityOfDetroit/bloom/issues/227#issuecomment-887839372 has this mapping for the fields in the existing HRD spreadsheet. This ticket is aimed at doing something similar for the fields in the property manager survey that we've recently sent out; I don't think that mapping exists anywhere.

**Comment by anders-schneider** [comment]
The top-level bullets below show the text of the questions in the property manager survey. The "examples" sub-bullet shows example inputs, and the "mapping" sub-bullet indicates which field(s) this will correspond to.

- Which other income-restricted unit types do you have in this property? Check all that apply. [Studio/1 Bedroom/...]
   - Examples: "40% AMI", "30% AMI or below", "35% AMI, 40% AMI, 60% AMI"
   - Mapping: for each AMI percentage, these will be new rows in the **`UnitsSummary` table** (note that HRD decided not to ask for counts of units at a specific AMI level, so `UnitsSummary.totalCount` will have to be null.

- Does this property have an open waitlist? Write in the "other" line if you have multiple waitlists and for what kind of units.
   - Examples: "Yes", "No", "One for regular apartments/one for section 8"
   - Mapping: **`Listing.isWaitlistOpen`** (note that we'll need to do some manual data processing to handle the "other" responses, or make assumptions in our import script)

- Provide a link to the application for your property. 
   - Examples: "https://www.samaritas.org/Portals/0/Samaritas-Pre-Application-Form-2021.pdf", "n/a"
   - Mapping: **`Listing.applicationLink`** (note: this field doesn't yet exist and must be created)
 
- Does your building offer any of the following accessibility features? These answers will help residents with disabilities understand if this property can meet their needs.
   - Examples: "Handicapped parking spots", "Elevator, Laundry room, Allows service animals, Handicapped parking spots, Doorways to property are big enough for a wheelchair, Units accessible for those with mobility-related disabilities"
   - Mapping: **`Property.accessibility`**
   - Note: there is a separate set of questions that seem to ask about these things one-by-one (e.g. "Do any units in your building have the following accessibility features for residents with disabilities? Please mark if the features are in all units, only certain accessible units, or both.  [Doorways to units are big enough for a wheelchair]"). We'll need to figure out which to consider the source of truth.

- What amenities does this property have?
   - Example: "Heating in units, Air conditioning in units (either central or unit AC is provided), Allows Cats, Allows Dogs, Laundry In Building, Parking on site, Community room in property, Tenants can pay rent online or by mail"
   - Mapping: **`Property.amenities`**

- Please provide a link to images of your property and floor plans.
   - Examples: "continentialmgt.com", "pvm.org" (notice that these are general property management websites, not links to specific images)
   - Mapping: **`Listing.image`**

- What is the cost of your application fee for all prospective tenants? Does it change depending on if the tenant is going into an income-restricted, affordable unit? 
   - Examples: "No fee", "$25 per adult", "$50" (notice that these are unstructured)
   - Mapping: **`Listing.applicationFee`**

- What is the cost of the security deposit needed to move in? Does it change depending on if the tenant is going into an income-restricted, affordable unit? 
   - Examples: "first months rent", "$499"
   - Mapping: **`Listing.depositMin` and `Listing.depositMax`** (or: we may want to add another field along the lines of `Listing.depositDescription`)

- What utilities is a resident in your building responsible for? Check all that apply. 
   - Examples: "Electric", "Gas, Electric", "Included in rent"
   - Mapping: **`Listing.costsNotIncluded`**

- What are your average utility costs at this property?
  - Examples: "$38", "35-60/month"
  - Mapping: also include this in **`Listing.costsNotIncluded`**

- Is this property reserved for any of the following populations? Check all that apply. 
   - Examples: "Seniors", "Family", "Seniors, Residents with disabilities, Veterans, Residents experiencing homelessness"
   - Mapping: **`Listing.reservedCommunityType`** (and we'll need to make sure the corresponding rows exist in the `ReservedCommunityType` table)

- If you have an age requirement to live in this building, please list it here.
   - Examples: "62+", "18 and up", "No" (notice that these are not constrained to be numbers)
   - Mapping: **`Listing.reservedCommunityMinAge`** (this mapping will either require the script to parse the text inputs, or we'll need to do some manual data cleaning first)

- Does this property offer permanent supportive housing? 
   - Examples: "Yes", "No"
   - Mapping: ??? (consult with HRD)

- Write down the address where residents can pick up a paper application for your property.
   - Examples: addresses...
   - Mapping: **`Listing. applicationPickUpAddress`**

- What is the minimum/maximum rent for a Studio/1BR/2BR/... apartment?
   - Examples: "$700", "Income based", "No minimum"
   - Mapping: these will be rows in the **`UnitsSummary` table**. Two notes:
      - This data falls into two categories: "income based" and actual dollar amounts
      - We don't have the cross product of this data and the "AMI percentage per unit type" data. But many of the unit types only exist at a single AMI percentage, so it should be possible to infer the cross product.

**Comment by willrlin** [comment]
* Provide a link to the application for your property.
  * This is already supported via the `Listing.applicationMethods` with `ApplicationMethodType.External`.
* Permanent supportive housing
  * Safiya has said that this will be a later addition to the site; I don't think we need to do anything regarding these right now.

**Comment by willrlin** [comment]
Also note that accessibility on the frontend is derived from `Listing.accessibility` and NOT `Property.accessibility`.
