### ISSUE TITLE
Validate listing.managementWebsite

### ISSUE THREAD

**Issue by anders-schneider** [CityOfDetroit/bloom#400]
When we upload listing data, we should verify that the management Website that we're provided is a real website url. We might also want to validate it at the point where we're using `listing.managementWebsite`.

https://www.npmjs.com/package/isurl might be helpful.

**Comment by willrlin** [comment]
Note: Bloom has a "urlRegex" in `ui-components/src/helpers/validators.ts`. We probably want to use a library, but FYI that it's there.
