### ISSUE TITLE
If all properties are filtered out, show a message

### ISSUE THREAD

**Issue by willrlin** [CityOfDetroit/bloom#401]
If you select a filter where all properties get filtered out, we should show a message to that effect.

**Comment by willrlin** [comment]
@tomgebauer - I don't see a sample message like this in the mocks. Let us know on this ticket what we should say in the case where all properties get filtered out.

**Comment by tomgebauer** [comment]
![image](https://user-images.githubusercontent.com/3886741/129394338-bae2ef39-54af-4084-b759-d831eff40ebe.png)
Link to Figma mock [Filter 1.0.2, applied, no results](https://www.figma.com/file/wAhoXVmHRIJ2TyBKFVq2JY/Desktop-and-Mobile-Experiences?node-id=2579%3A5990)
