### ISSUE TITLE
"How to apply" section in the individual-listing view

### ISSUE THREAD

**Issue by anders-schneider** [CityOfDetroit/bloom#403]
The current individual-listing view has only two things in the right rail ("last updated" and "management company"):

![image](https://user-images.githubusercontent.com/8754454/129400428-54a9fcf5-da32-4bd2-b789-cf04da2a250e.png)

And on mobile, the "Process" section only includes "management company":

![image](https://user-images.githubusercontent.com/8754454/129400562-ff08e772-c189-4b50-b6c1-fe7538e3b20c.png)

Our mocks include a "How to apply" section:

![image](https://user-images.githubusercontent.com/8754454/129400806-b65a6647-f7cd-4c5c-844d-772311a81c84.png)

This ticket tracks adding that "How to apply" section. Here are the relevant fields in the `Listing` model that could be exposed there:

- Property Phone number --> listing.property.phone_number
- Project Address --> listing.property.building_address.street
- Zip Code --> listing.property.building_address.zip_code
- Latitude --> listing.property.building_address.latitude
- Longitude --> listing.property.building_address.longitude

But there's an assumption in there: *this assumes that the property address is the correct place to pick up an application*. We should verify that assumption before declaring that that's true.

I don't think we want the "Go to online application" link because we don't have those urls.

**Comment by anders-schneider** [comment]
@tomgebauer Is there anything you'd add/amend to this ticket?

**Comment by anders-schneider** [comment]
@willrlin should we pull this into M10?

**Comment by pfeeny5** [comment]
Linked draft PR#432 to this ticket.  There are a few fields that we can leverage to get an address or contact information for applications.  `listing.applicationPickUpAddress` and `listing.applicationAddress`.  @willrlin do we have a preference?
@tomgebauer is there anything else you would like to include in this section based on your mockup, or for when we don't have an address?

**Comment by anders-schneider** [comment]
A note: we're not populating any of the application addresses (`listing.applicationAddress`, `listing.applicationPickupAddress`, `listing.applicationDropOffAddress`, or `listing.applicationMailingAddress `) because we don't know them - the only address we know for sure is the actual address of the property. It may be worth checking with HRD to see if we can assume that the actual property address could be used for e.g. `applicationPickupAddress`, but AFAIK we can't make that assumption at the moment.

In terms of data fields that don't show up anywhere else in the `ListingView`, the only one that comes to mind is `listing.phoneNumber`. Maybe we only display that in this section? And/or say: if that doesn't work, contact the management company (since there's a "Management Company" section with more details about how to get in touch with the management company).

**Comment by willrlin** [comment]
I think some of that information could be in the Rentlinx data, so I don't think we should exclude those applications addresses if they theoretically could be populated. It might be good to check `listing.applicationPickUpAddress` and if not that one, use the building address, and if that's not available, use a "contact management company" fallback. Phone number, I don't really have any preference on what we use.

**Comment by pfeeny5** [comment]
I've updated the draft PR to include a waterfall if statement.  First it looks for `listings.applicationPickupAddress`, then `listings.applicationAddress`, then `listing.buildingAddress`, and finally the default "Contact Management Company" message.  We can pull out any one of those once we confirm with HRD.
