### ISSUE TITLE
`listing-importer.ts` creates two properties for each one listing (they should be 1:1)

### ISSUE THREAD

**Issue by anders-schneider** [CityOfDetroit/bloom#406]
How to reproduce: run any of our listing importer scripts, and check `select count(*) from property;` before and after.

**Comment by anders-schneider** [comment]
Summarizing what I know about this before heading out:

- `listing-importer.ts` uploads a new property once when it calls `uploadProperty`, and another property is created when it calls `uploadListing` because the backend `ListingsService.create` creates a new property from the passed-in `ListingDto` ([link](https://github.com/CityOfDetroit/bloom/blob/303688b411124999fd32373a877e11d0e665313e/backend/core/src/listings/listings.service.ts#L152)).
- Okay great, so we can just remove the call to `uploadProperty`, right? Nope: the `PropertyCreateDto` created from the `ListingDto` in `ListingsService.create` doesn't include any of the fields that the original input `listing.property` had (e.g. "region", "phone_number", etc.). This is possibly because the `PropertyCreateDto` doesn't include any fields other than `units` and `buildingAddress` ([link](https://github.com/CityOfDetroit/bloom/blob/303688b411124999fd32373a877e11d0e665313e/backend/core/src/property/dto/property.dto.ts#L32))?
- So how does one upload a property and upload a listing, without creating two properties? One idea I'm trying now: upload the listing, and then update the created property after that. The issue I'm running into there: the `Listing` returned from `uploadListing` doesn't include the property (I'd wanted to grab the id from `listing.property.id`). So do I do something complicated like "search for the property that corresponds to this listing, retrieve it, and update it to include the fields the input property has"?

**Comment by willrlin** [comment]
I haven't digested everything in your note, but you could look at the seeder script, which does do something like what you're suggesting above.

**Comment by anders-schneider** [comment]
The fields that are impacted by this:
- listing.property.phone_number (added by us; not present in Exygy's code)
- listing.property.region (added by us; not present in Exygy's code)
- listing.property.neighborhood (added by Exygy; present in their code too)

So one way to fix this (which is in line with Exygy's plans to have `Listing` eventually absorb `Property`'s fields) would be to just migrate our fields (`phone_number` and `region`) to be fields in `Listing` instead of in `Property`. That will still leave us unable to upload a `neighborhood` until Exygy does actually make that field live within `Listing` instead of `Property`, but that seems worth it to save us effort that will eventually be obsolete.
