### ISSUE TITLE
Pending changes to `backend-swagger.ts`

### ISSUE THREAD

**Issue by anders-schneider** [CityOfDetroit/bloom#421]
When I run `yarn generate:client` in `backend/core` on a clean version of our `main` branch, there are significant changes to `backend-swagger.ts` (I think ~1500 lines?). I don't recognize the changes, and it looks like they might correspond to a couple different areas of the codebase. Also, with these changes, we get "compiler" errors in `backend-swagger.ts`.

All of this represents tech debt: each time we make a change that requires an update to `backend-swagger.ts`, we have to run `yarn generate:client` and then revert all of the changes that aren't related to whatever feature we're working on.

I only looked at this for ~10min, but it might be worth our while for someone to look at this in more depth and see if we do need changes to `backend-swagger.ts`, how to resolve those compiler errors, and how to get to a state where when we run `yarn generate:client` in `main` we don't get any changes to `backend-swagger.ts` (that's the "done criteria").

**Comment by willrlin** [comment]
I did a quick check and it seems like it was caused by the recent upstream merge (before that, we don't have any pending backend-swagger changes.

**Comment by willrlin** [comment]
I ran `generate:client` on `upstream/dev` and it looks like they have the same pending changes.

**Comment by willrlin** [comment]
@seanmalbert - did you have upstream changes that you haven't reconciled with `backend-swagger` yet?

Example:
```
types/src/backend-swagger.ts:4971:3 - error TS2687: All declarations of 'amiChart' must have identical modifiers.

4971   amiChart?: CombinedAmiChartTypes
       ~~~~~~~~

types/src/backend-swagger.ts:5072:3 - error TS2687: All declarations of 'applicationDropOffAddress' must have identical modifiers.

5072   applicationDropOffAddress: CombinedApplicationDropOffAddressTypes
       ~~~~~~~~~~~~~~~~~~~~~~~~~

types/src/backend-swagger.ts:5075:3 - error TS2687: All declarations of 'applicationMailingAddress' must have identical modifiers.

5075   applicationMailingAddress: CombinedApplicationMailingAddressTypes
       ~~~~~~~~~~~~~~~~~~~~~~~~~

types/src/backend-swagger.ts:5087:3 - error TS2717: Subsequent property declarations must have the same type.  Property 'leasingAgents' must be of type 'User[]', but here has type 'UserBasic[]'.

5087   leasingAgents?: UserBasic[]
       ~~~~~~~~~~~~~

  types/src/backend-swagger.ts:3765:3
    3765   leasingAgents?: User[]
           ~~~~~~~~~~~~~
    'leasingAgents' was also declared here.

types/src/backend-swagger.ts:5090:3 - error TS2717: Subsequent property declarations must have the same type.  Property 'jurisdiction' must be of type 'Id', but here has type 'Jurisdiction'.

5090   jurisdiction?: Jurisdiction
       ~~~~~~~~~~~~

  types/src/backend-swagger.ts:3753:3
    3753   jurisdiction?: CombinedJurisdictionTypes
           ~~~~~~~~~~~~
    'jurisdiction' was also declared here.
```
