### ISSUE TITLE
Add "buildling description" to data model (or find an existing field for it), import scripts, and frontend

### ISSUE THREAD

**Issue by anders-schneider** [CityOfDetroit/bloom#425]
The HRD listing spreadsheet has a column for "Building Description" with comma-separated values like:

"Walk-Up, Garden Style"
"Multifamily apartments"
"Single Family Homes"

and others. We don't currently import or display this data. I'm not sure if there's an existing field where this fits, but if not we should add a field to the `Listing` model for it.

Done criteria: this data is stored in our DB and displayed in the appropriate places in the frontend.

Also add this to the seed data.

**Comment by willrlin** [comment]
Does the Rentlinx data also have this? Just thinking about how much value this adds and whether we would expect to get this data ongoing in the future or if it would only come in once with the HRD spreadsheet.

**Comment by anders-schneider** [comment]
Rentlinx ([API docs](https://www.rentlinx.com/docs/datalinx)) has a `<PropertyType>` element that looks like it can have similar info:

![image](https://user-images.githubusercontent.com/8754454/130094815-0bf81f5a-a706-4cce-9d2a-2121715c759f.png)

But if we can get it from the HRD spreadsheet, do we care if we can get it from Rentlinx, too? I suppose for new listings this might matter. But for existing listings, it seems like this is a field that would never change.

**Comment by willrlin** [comment]
Yes, I was thinking about new listings in the future and whether we would be able to map this field automatically from another dataset or if it was just from the spreadsheet and would have to manually be entered in. Would we have this as an enum or string or what? I think for this issue we could contribute it upstream first since it's not urgent.

**Comment by anders-schneider** [comment]
Contributing upstream first sounds right to me!

On enum vs string vs other: maybe array of one or more enum values per listing? That would let us filter on it, and the HRD spreadsheet data seems to only include a handful of values. But we should be aware that the HRD data has values with typos like "Aparments", so some data cleaning might be in order.

**Comment by willrlin** [comment]
Rentlinx seems to support multiple values per listing and they have a list of enums, so that sounds like the right approach. One concern I have is that "senior" is one of the enums in the Rentlinx data, so it could start to get conflated with reserved community / preference types.
