### ISSUE TITLE
Validate management company website on import/update

### ISSUE THREAD

**Issue by anders-schneider** [CityOfDetroit/bloom#450]
We currently make sure that each management company website is prefixed by "http" in the frontend ([link](https://github.com/CityOfDetroit/bloom/blob/bd91b7e76a5ee3a3e709e2e03ed01d38c332ef1a/ui-components/src/page_components/listing/listing_sidebar/LeasingAgent.tsx#L25)). We should do this (and maybe other is-this-a-valid-URL checks?) when importing/updating data instead.

**Comment by ludtkemorgan** [comment]
This is covered in core already
