### ISSUE TITLE
Import script: filter out listings that are not "Existing Occupied" or development pipeline level 3+

### ISSUE THREAD

**Issue by anders-schneider** [CityOfDetroit/bloom#453]
Not all listings in the HRD spreadsheet are currently available for people to move into; our import script should be updated to filter out those that are unavailable. The filter criteria:
- In the "Project Type" column, we should keep all listings that are "Existing Occupied"
- For those that are not "Existing Occupied", we should keep the listings for which "Development Pipeline Bucket" has a value of 3 or above.

**Comment by anders-schneider** [comment]
Note: the field that we're concerned with here ("Project Type") isn't present in the spreadsheet in Box (not even in the "All Fields" tab). It _is_ present in the "Master Data Sheet" that Safiya sent via email; I'd like to figure out if it's possible to upload that spreadsheet to Box as well. @willrlin do you know the answer to this? (If not I'll email Safiya)

**Comment by willrlin** [comment]
I would email Safiya. It's possible that it can't be in box and must only exist locally until we upload all the data to the website.
