### ISSUE TITLE
Consider displaying estimated rent

### ISSUE THREAD

**Issue by willrlin** [CityOfDetroit/bloom#462]
With the eligibility questionnaire determining the user's AMI, and us knowing the AMI chart for Detroit that contains information about how much rent can be charged based on the number of bedrooms and the AMI percent, we could potentially display an "estimated" rent for the user.

@elenm brought this up in #236.

**Comment by willrlin** [comment]
@tomgebauer @kar-r-green - this isn't in the PRD, but if we don't get rent numbers from property managers, perhaps we could consider adding this feature in Q4?

**Comment by kar-r-green** [comment]
Great idea @willrlin -- I will add to Feature Requirements 5b in the PRD. Please leave in Q4.
