### ISSUE TITLE
Import "Special Needs / Disabled" field

### ISSUE THREAD

**Issue by anders-schneider** [CityOfDetroit/bloom#465]
Update the CSV import script to upload the "Special Needs / Disabled" field.

Questions:
- Should we also look at the HUD compliance column? (It may say "wholly special needs" or something like that)
- Should we upload it as a reserved community type or a preference?

**Comment by willrlin** [comment]
I think we could start working on this, but we'll need confirmation from HRD about which of the properties are exclusive to special needs. If they are exclusive, we would use the reserved community type. If not, use the preference. We could initially use the HUD compliance column pending that confirmation.

**Comment by anders-schneider** [comment]
Answers to questions in first comment:
- Let's assume we're only looking at the HUD compliance column (for "wholly elderly")
- Reserved community type
