### ISSUE TITLE
Analyze support for RTL languages

### ISSUE THREAD

**Issue by avaleske** [CityOfDetroit/bloom#47]
Part of CityOfDetroit/affordable-housing-app#98 

It'd be good to analyze Bloom's support for RTL languages. What work needs to be done to support arabic?

Also: Check with Exygy about their roadmap for RTL languages.

Done: A doc, or the necessary tickets, or comments on the styling epic, with what we need to do to support RTL languages.

**Comment by willrlin** [comment]
Assigning to @elenm for initial visual check. If anything else is required, someone else will need to pick that up.

**Comment by elenm** [comment]
RTL support needs further work. 

Here are some views: 
![image](https://user-images.githubusercontent.com/16543000/125642855-0cae8268-dc7e-46b1-b489-ccd733046157.png)
![image](https://user-images.githubusercontent.com/16543000/125642890-0fc24d5d-a2b1-4e95-953e-f625949febc2.png)
![image](https://user-images.githubusercontent.com/16543000/125642950-c8a9bd94-1b4c-4fff-926e-2ff1b80f1db8.png)
![image](https://user-images.githubusercontent.com/16543000/125643024-ae88dcb8-71fa-4265-b1a9-91b35225c0b0.png)
![image](https://user-images.githubusercontent.com/16543000/125643090-1da5b347-3d82-4758-8155-df4e64442368.png)
![image](https://user-images.githubusercontent.com/16543000/125643565-b8fad906-0aa4-47cb-ae29-0c1e55b62be9.png)
![image](https://user-images.githubusercontent.com/16543000/125645192-ae68474e-0677-426a-a765-803c4aedf6eb.png)
![image](https://user-images.githubusercontent.com/16543000/125645216-29e7b709-f642-4686-b624-145dd98f0272.png)
![image](https://user-images.githubusercontent.com/16543000/125645242-8d5303d6-7204-4d5a-add4-4bdce2080787.png)
![image](https://user-images.githubusercontent.com/16543000/125646128-d3736809-27f6-4081-8d65-134abfefce06.png)
![image](https://user-images.githubusercontent.com/16543000/125646161-a0c9b265-791c-47ab-b286-80ecf3a268b5.png)
![image](https://user-images.githubusercontent.com/16543000/125646174-b8e4f451-1b28-4533-b3c8-46056cc8901d.png)

**Comment by avaleske** [comment]
Thanks for doing this! While you're there, can you also check the appearance with an RTL locale like arabic? I wonder if some of the errors are cause divs down the tree are still trying to flow LTR for english.

**Comment by elenm** [comment]
I tried setting the default language to 'ar' here: https://github.com/CityOfDetroit/bloom/blob/70ea2a6c039cbf88e06ce0c9ce36a156c1bbd9cb/sites/public/next.config.js#L57
Nothing changed, so I'm not sure if I need to do something additional or if there is no special functionality for RTL languages.

**Comment by willrlin** [comment]
Maybe we first need translations? We could send an initial JSON file to DoIT's vendor.

**Comment by elenm** [comment]
Should that be part of this issue or a separate one to set up our translations?

**Comment by willrlin** [comment]
Definitely separate issue, but I was just thinking maybe it wasn't working when you were testing because we didn't already have the translations. I think the initial work is done, now it's just a matter of fixing them.

**Comment by avaleske** [comment]
Assigning to @avaleske to write tickets for the work

**Comment by avaleske** [comment]
I created #243, #244, #245, #246, #247, and #248 to capture the issues you found, @elenm. Reassigning back to you and then closing.
