### ISSUE TITLE
Epic: Styles + Layout

### ISSUE THREAD

**Issue by avaleske** [CityOfDetroit/bloom#48]
For tracking styling and layout work

- [x] #62
- [x] #47
- [x] #111
- [ ] #136 
- [ ] #243
- [ ] #244
- [ ] #245
- [ ] #246
- [ ] #247
- [ ] #248
- [x] #543
- [ ] #564

**Comment by willrlin** [comment]
Chatting with Safiya and other TLs and we should aim to bring our deployed site much closer to the mocks in M8 to enable user testing in August.

**Comment by willrlin** [comment]
@kar-r-green @tomgebauer if you want to put major differences between the mocks and the deployed site that we want to prioritize fixing in M8, please add comments here or link newly created tickets.

**Comment by GabeBenjamin** [comment]
The design has changed so this is mostly finished and/or obsolete now.
