### ISSUE TITLE
[Eligibility Questionnaire] Elderly and Special Needs eligibility filtering data and product questions

### ISSUE THREAD

**Issue by elenm** [CityOfDetroit/bloom#488]
Outstanding product questions and verification we need to do: 

- Data verification: Verify that "elderly" and "special needs" are eligibility requirements for each of the properties in the corresponding HUD compliant group. I did a cursory search of a couple of properties and the information is available online. We may need to call the properties if the information is not available online.

- Data verification: Verify which other non-HUD properties have "elderly" and "special needs" as a requirement. This can involve an online search or phone calls to the property.

- Data verification: Determine the age threshold for each "elderly" property (62 or 55).

- Data verification: Are there any properties that require you to be both elderly and have a disability to apply?

- Product question: Do we want to have a special category for partially elderly properties?

- Product question: Do we want to have more specific categories for "special needs" properties? Some are specific to people with a mobile impairment or mental illness.

See #317 for more information

**Comment by kar-r-green** [comment]
Responding to Product Questions:

Product question: Do we want to have a special category for partially elderly properties?
_Response: Yes please, confirming, let's add a separate category of 'partially elderly' (or similar to match existing naming convention) to indicate to the resident that it's not an entirely senior-living facility._ 

Product question: Do we want to have more specific categories for "special needs" properties? Some are specific to people with a mobile impairment or mental illness
_Response: How often is this specification called out in data collection? Given this level of information may not be available for all propertied, my recommendation is to keep a generic 'special needs' category, but to include specifics in the unit summary description, where specifics exist. @elenm please let me know if you disagree or have another suggested workaround. Thanks!_

@elenm do you need assistance unblocking the data questions with HRD? Happy to assist.

**Comment by willrlin** [comment]
I sent the list of properties over to Safiya that need verifying and I believe the intention was to verify the age threshold and whether these are requirements for the communities or preferences.

**Comment by elenm** [comment]
Thanks Kar! I'm assuming we also want to add filtering for the partially elderly properties? Should we add it as another community type in the filtering modal?

![image](https://user-images.githubusercontent.com/16543000/131547716-758eef5e-0744-442b-a4a3-958f35ecb867.png)

**Comment by kar-r-green** [comment]
Yes, let's try the following options:
1. Community Type > All
2. Community Type > 'Varied housing (including senior 62+ options)'
3. Community Type > 'Senior housing (62+ only)'
4. Community Type > 'Special Needs and disability'

@tomgebauer @elenm open to feedback on language use on 2 and 3
