### ISSUE TITLE
Mismatched constraints between backend and frontend, for listings views

### ISSUE THREAD

**Issue by anders-schneider** [CityOfDetroit/bloom#50]
The listing importer scripts uploaded unit/property/listing data that the frontend wasn't able to display (because the frontend expected the data to conform to certain requirements). We should either tighten the constraints on what the backend will accept, or make the frontend resilient to the data accepted by the backend (or, probably, some combo of the two). As we decide whether to change the frontend vs. backend, we could use the HRD data as a guide.

First step: list the ways the frontend broke because of unmet data-format expectations.

Done criteria: we never get a frontend error for data that was accepted by the backend. To narrow the scope a bit, let's focus this issue on the `/listings` and `/listings/{id}` views.

**Comment by willrlin** [comment]
One thing to also keep in mind: does this affect the validation in the forms for editing these in the property manager portal? I wouldn't want us to break that validation in the forms for required fields.

**Comment by anders-schneider** [comment]
I futzed with `minimal-listing.json` for a while and ultimately wasn't able to have anything accepted by the backend that broke the frontend (note: I only looked at the listings overview and listings detail pages). Maybe our/Exygy's changes fixed the gaps I saw when I first was uploading listings?

What I did: created https://github.com/CityOfDetroit/bloom/pull/288 to trim down `minimal-listing.json` so that it is the true "minimal listing" (i.e. it only includes fields that are required by the backend).

Two possible next steps:
- Import this new `minimal-listing.json` and make sure that the property manager portal doesn't break? (per Will's comments) If the property manager portal *does* break, then we need to either remove make the partner portal behave more gracefully in the absence of certain fields, or tighten the constraints on the backend.
   - Note: I think to really test this, we'll want to associate the "Minimal Listing" with a certain property manager, and then log in as that property manager. This may take a little futzing on the backend or in the DB.
- Look at the listings overview page and the listings detail page and figure out which UI components need to be changed to more gracefully handle the absence of certain fields. Or: for data that we absolutely do want, add constraints to the backend.

**Comment by anders-schneider** [comment]
The "done criteria" from the first comment are met, and the work to "more gracefully handle the absence of certain data" is tracked in https://github.com/CityOfDetroit/bloom/issues/228 - closing this.

**Comment by willrlin** [comment]
Hm, in the process of working on #341, I believe that I supplied all the information in the seed listings needed (from looking at minimal listings), but I'm getting an error when I try to load the individual unit page: `Cannot read property length of null`.

**Comment by willrlin** [comment]
Just re-opening to track this.

**Comment by willrlin** [comment]
Ah, I discovered that when you specify a `reservedCommunityType`, you must also specify a `reservedCommunityDescription` (even though it looks like there are some duplicate fields inside `reservedCommunityType`)
