### ISSUE TITLE
[Bug] 'Apply Filter' button missing on mobile - P1

### ISSUE THREAD

**Issue by kar-r-green** [CityOfDetroit/bloom#507]
STEPS TO REPRODUCE:
On mobile device, the 'Apply Filter' button is hidden and the user is not able to scroll down to see it. 
Site location: https://sites-public-tj3gg4i5eq-uc.a.run.app/listings?page=1

EXPECTED RESULTS:
On mobile device, user should be able to see / click 'Apply Filter' button.

OBSERVED RESULTS: Experienced during user testing on resident's mobile device.

ADDITIONAL INFORMATION: n/a

**Comment by willrlin** [comment]
You weren't able to scroll down? Is this on a real device or on Chrome emulated as a mobile device?

**Comment by kar-r-green** [comment]
I was not able to recreate on Chrome emulated, so it may be mobile-device specific. Acquiring device specifications from Grady who submitted the bug for review. Please standby.

**Comment by kar-r-green** [comment]
Confirmed this was resident reported, using an iPhone / iOS system and the button was not visible. The user was unable to scroll down to it. Could this possibly be a iOS system issue resolvable by a software upgrade / reset? If so, I can suggest this to Grady to share with the resident.

**Comment by willrlin** [comment]
I don't know how this could be the case - do you think the resident just wasn't _able_ to scroll it or was trying to scroll on the side instead of inside the filter modal? I've tried reproducing this but can't.

**Comment by kar-r-green** [comment]
Since we cannot reproduce, will close out. Spoke to Grady and he will keep an eye out for any similar feedback, assuming it was user error. Thanks!
