### ISSUE TITLE
Listing photo(s) strategy

### ISSUE THREAD

**Issue by anders-schneider** [CityOfDetroit/bloom#51]
This issue tracks scoping out our strategy wrt showing photos for listings. A couple of ideas/questions:
- How does Bloom host listing photos? (for dev and prod deployments)
- Do we want to have a single photo per listing, or multiple? Can a listing have zero photos?
- There is some interaction here with the "data gaps" work that Grady is leading; i.e. our photos strategy should maybe depend on what we can get from property managers
- Tom has thought a lot about listing photos and user testing

One possible intermediate outcome here: prototypes of different photo strategies (i.e. hosting photos on S3 vs. as static assets, or single photo vs. photo carousel)

Done criteria: an articulated strategy wrt listing photos (this could be a doc, a series of Github issues, or something else), and approval from Grady, Tom, and SWE team.

**Comment by willrlin** [comment]
One idea I had was that we should use the Drupal site as image hosting. Maybe @jedgar1mx could help us get the right APIs to use for uploading and getting the URL.

**Comment by anders-schneider** [comment]
Note: Exygy added an [`image` field](https://github.com/CityOfDetroit/bloom/blob/a973d1295811ea490eaa17f3f1052d24752fa5c5/backend/core/src/listings/entities/listing.entity.ts#L433) to the `Listing` entity, which references an [`Asset`](https://github.com/CityOfDetroit/bloom/blob/main/backend/core/src/assets/entities/asset.entity.ts). Two observation:
- Listing is ManyToOne with images, so there can be only one image per listing, but the same image can be used for multiple listings (I'm surprised by this).
- This new `image` field isn't yet used with the sample data that's populated by `yarn db:reseed`; the images for those listings are still stored as JSON blobs in the Listing's [`assets` field](https://github.com/CityOfDetroit/bloom/blob/a973d1295811ea490eaa17f3f1052d24752fa5c5/backend/core/src/listings/entities/listing.entity.ts#L90), with values like:

```
{
  "label": "building",
  "fileId": "https://regional-dahlia-staging.s3-us-west-1.amazonaws.com/listings/triton/thetriton.png"
}
```

**Comment by willrlin** [comment]
I highly recommend we start a conversation with them on the Q&A about this. I assume they're going somewhere with this, so let's figure out what they're planning and how that fits with our plans.

**Comment by willrlin** [comment]
Maybe as a part of this task we can get some photos of actual Detroit homes to use as placeholders.

**Comment by anders-schneider** [comment]
See https://github.com/bloom-housing/bloom/discussions/1400#discussioncomment-1010632 for the current status of this work on Exygy's side. From that, and my understanding of Detroit's goals wrt photos, I don't think there is any immediate work for us to do in this space (it would likely just duplicate what Exygy is doing). There is one thing we could do (https://github.com/CityOfDetroit/bloom/issues/212) if we want to unblock the ability to have multiple photos per listing.

So: I think our "photos strategy" is mostly decided (use what Exygy is building, maybe contribute to allow for multiple photos per listing). I expect that there will be smaller, tactical pieces of work that we might want to do to support photos (create a hacky, backdoor way to upload photos, just until Exygy's photos support lands), but we'll create the tickets for those as the need arises.

**Comment by willrlin** [comment]
Do we think it's worthwhile to scope out using Drupal as the photos hosting provider such that Detroit wouldn't need to purchase any storage?
