### ISSUE TITLE
Flesh out frontend filtering by income/AMI

### ISSUE THREAD

**Issue by abbiefarr** [CityOfDetroit/bloom#515]
Flesh out AMI filtering on the frontend

Initial work to add AMI filtering on the frontend was in #645, but this was just a v0 that still requires users to know what AMI is. We can do better by adding more context, or adding a small AMI calculator to the filter modal, or both.

Some initial brainstorming on how to add an expandable div that shows a longer explanation of AMI was [here](https://github.com/CityOfDetroit/bloom/issues/515#issuecomment-928324060) but it doesn't include any information about household size, and requires some changes to UI components so we can change the "read more" text on the expandable component, so it was set aside near the end of cohort 1.

Work:
- Add AMI filtering to the frontend, in a way that doesn't require users to know their AMI (but could allow them to set it if they do know)
- We should be able to leverage other code that does the AMI calculation.
- We'll need to handle the case where only income or household size is provided, and add a helpful error message.
- Adding a tooltip or explanation with language like "Some housing is reserved for people below certain incomes. Your AMI percentage is used to determine what housing you qualify for, and depends on your household size and income."
- Right now, the frontend uses a `minAmiPercentage` queryparam to store the current AMI percentage filter state. We can't figure out the income and household size from the AMI percentage, so we'll need to pick which "wins" if a user specifies both ami and income + household size.

Context:
- A person's Area Median Income percentage (AMI) is calculated based on their income and household size, based on [this](https://detroitmi.gov/sites/detroitmi.localhost/files/2020-08/2020%20Income%20Limits.pdf) table. For example, a person with a 2 person household and income of $25,120 has an income that is 40% of AMI
- This qualifies them for housing that is designated for people with 40% or more of the AMI.
- If someone has an income of $23,000, should we round up to 40% because they can't qualify for properties that require them to make less money.

Mocks:
The filter with an AMI option:
![image](https://user-images.githubusercontent.com/1295824/134739157-be262de7-4925-4631-93e1-e17687802940.png)

Similar language in the eligibility questionnaire
![image](https://user-images.githubusercontent.com/1295824/134739991-116eacbb-f910-4ea8-94d7-bad6d789f065.png)

---
Old issue content:
Blocking question: what does the UI and user flow look like for income/AMI filtering?

One idea is to have a numeric field for income in the filter modal and perform the AMI calculations before sending the request to the backend. So the backend will need to already support filtering by AMI (tracked in #478)

**Comment by willrlin** [comment]
@kar-r-green @tomgebauer - this is not something that shows up in the mocks (just the rent price filtering does), but wanted to hear what you thought. Should we have an income input in the filter that then filters out listings that don't have any units with AMI meeting your needs?

Also given that most of our listings will likely have AMI information but not rent information.

We will already have this from the eligibility questionnaire, this is just if we want to also have it in the filter modal.

**Comment by kar-r-green** [comment]
@willrlin Yes, ideally we should we have an income input in the filter that then filters out listings that don't have any units with AMI meeting your needs. @tomgebauer welcome your POV

How do you recommend we proceed? Can this be addressed in M12 or should we move to Q4 given the lift?

**Comment by willrlin** [comment]
It shouldn't be a problem to do since we're already doing this calculation/filtering for the eligibility questionnaire. We just need a design in the mocks for the filter modal.

**Comment by willrlin** [comment]
And also the question of what should happen if the user selects BOTH a rent range AND an income. Do we filter for listings that have EITHER a rent in that range OR units within the user's AMI?

**Comment by kar-r-green** [comment]
EITHER so more units show even if they have a low AMI, if they have a higher rent range they defined themselves, I think we should show both.

**Comment by avaleske** [comment]
@tomgebauer and @kar-r-green:
So just to make sure I understand, here's my plan so far:
- Have a drop down with different AMI levels in the filter modal.
- The ami dropdown might get set by the eligibility questionnaire, or a user could set it themselves directly if they already know their AMI.

Does that make sense with how AMI works? Your AMI doesn't change based on the number of bedrooms you want, but it does change with your household size, so we might need to prompt the user in some way if they change their household size or something?

**Comment by willrlin** [comment]
Another idea is to have income/household number in the modal somewhere and do the AMI calculation. It could be a separate modal with more information (tooltips?) about what this is doing and why the information is needed.

**Comment by kar-r-green** [comment]
sorry for the delay while I was OOO

Yes @avaleske the way you outline it here is how we originally scoped this filtering option.

However, +1 to Will's solution to cover off on cases where the resident may not be aware of their AMI. Could we do both / break out a new task for Will's solution? @willrlin is what you suggest connected to the income calculator #79 (-- or should it be?).

@tomgebauer still hoping for your feedback from a UX and user experience lens. Thanks!

**Comment by willrlin** [comment]
I wasn't initially thinking of the income calculator, but that makes sense to do something in that vein. I was imagining a simple modal with only the household number and income, possibly with explanations about income (essentially just those two pages of the eligibility questionnaire).

**Comment by kar-r-green** [comment]
Got it - simple modal makes sense as you've laid out here.

Let's keep it as you describe and evaluate income calculator integration in Cohort 2 or future phases. Let me know if I can clarify further.

**Comment by avaleske** [comment]
I've updated the issue with some mocks and what we've determined.

**Comment by avaleske** [comment]
Notes from experimenting with the `<Select>` component's label to provide a expandable div that has additional context on what AMI is:

If we want to add expandable details to a label, we need to update the Select's label prop type to be `string | React.ReactNode`

Then we can pass in a prop like
```
              label={
                <span>
                  {t("listingFilters.minAmiPercentageLabel")}
                  <ExpandableContent>
                    <div>
                      <p>
                        Some units are set aside for people with incomes below a certain percentage of
                        the Area Median Income, or AMI. For example, if your income is 45% of the Area
                        Median Income, you qualify for units set aside for people 45% AMI, 50% AMI,
                        55% AMI, and greater.
                      </p>
                      <p>
                        If you don't know what AMI percentage your income falls into, use the Do I
                        Qualify tool to find out.
                      </p>
                    </div>
                  </ExpandableContent>
                </span>
              }
```

To get an expandable thing like
![image](https://user-images.githubusercontent.com/1295824/134990356-1878111d-decf-41bd-92ef-24e81cdbac77.png)

and
![image](https://user-images.githubusercontent.com/1295824/134990341-ff45be12-6b4c-47b8-8895-767a8d8dc203.png)

**Comment by avaleske** [comment]
Unassigning myself, since this work will be for cohort 2
