### ISSUE TITLE
Contribute backend sorting upstream

### ISSUE THREAD

**Issue by avaleske** [CityOfDetroit/bloom#519]
- [ ] Contribute #542 upstream (but actually maybe wait on this because it would cause a behavior change for Exygy; combine it with the next item)
- [ ] Contribute the PR that augments the param to allow for requesting an ordering on a specific field

**Comment by anders-schneider** [comment]
I sent https://github.com/bloom-housing/bloom/pull/1817 to Exygy, with the sorting changes so far

**Comment by anders-schneider** [comment]
The basic sorting framework (https://github.com/bloom-housing/bloom/pull/1817) is committed to Exygy's repo. I made a note in #561 and #562 (the follow-up sorting tickets) that those should be contributed upstream as well. Closing this.
