### ISSUE TITLE
Add sort buttons to frontend

### ISSUE THREAD

**Issue by avaleske** [CityOfDetroit/bloom#520]
Blocked on having additional things to sort by

**Comment by avaleske** [comment]
@tomgebauer where should sorting buttons go?

**Comment by tomgebauer** [comment]
@avaleske what are we able to sort by?

**Comment by avaleske** [comment]
PRD says by recency, but also pretty much whatever else you want to sort by (other than distance)

**Comment by anders-schneider** [comment]
Note: we currently only have one meaningful option for sorting (by "most recently updated"). So for now, I don't think it makes sense to have any frontend UI component for users to control sorting. Once #561 is finished, _then_ it would make sense to have a frontend component to let the user control how listings are sorted. (So I suppose this is "blocked" on #561.)
