### ISSUE TITLE
[Eligibility Questionnaire]: Change age question to binary / age range

### ISSUE THREAD

**Issue by kar-r-green** [CityOfDetroit/bloom#526]
Based on user feedback, change content of age question to binary y/n ('Are you over 62 years old?') or request to select age range.

Blocked by questions (Safiya to check into these items): 
1. Any other age range of importance aside from senior 62+
2. Can certain properties house seniors and caregivers of other age ranges?

**Comment by willrlin** [comment]
@kar-r-green @tomgebauer Should we just make an assumption for now and move forward?

Like a radio select with:
- 62+
- 55-61
- < 55
- Prefer not to say

**Comment by kar-r-green** [comment]
LGTM. @tomgebauer welcome your feedback
