### ISSUE TITLE
[Bug] 'Listings' link post-questionaire is non-functional

### ISSUE THREAD

**Issue by kar-r-green** [CityOfDetroit/bloom#527]
[REMEMBER: a bug should be understandable years later by someone who will never talk to the reporter or assignee.]

STEPS TO REPRODUCE:
1. Complete eligibility questionnaire
2. Click listings in the upper right corner
3. Link does not load

Location:
<img width="1174" alt="Screen Shot 2021-09-02 at 3 46 36 PM" src="https://user-images.githubusercontent.com/82838672/131909429-0ad4e1d1-492a-4ef5-b64d-64e44dd64d21.png">

EXPECTED RESULTS: Based on user feedback, clicking 'Listings' should redirect take the user to another view / back to 'All Listings.' This link confuses the user in its current state when by clicking 'Listings,' nothing occurs.

OBSERVED RESULTS: Clicking 'Listings' does not load anything new or take Resident to All Listings

ADDITIONAL INFORMATION: If this is operating as intended or if the 'Listings' link is part of the signed-in user epic / a future requirement, please close bug. Thanks!

**Comment by willrlin** [comment]
I think this probably was due to the fact that the eligibility questionnaire was not hooked up to anything at the time it was tested. I ensured that clicking on it after going through clears the filters and loads all the listings.
