### ISSUE TITLE
Replace "Minimum Income" column in summary table

### ISSUE THREAD

**Issue by abbiefarr** [CityOfDetroit/bloom#554]
`Minimum income` isn't a really valuable field for Detroit.

We could replace it with AMI (or AMI range). Alternatively, we could use a rent calculator to generate rent ranges from AMI and display that in the existing `Rent` column. If we go with the latter, we can use the space to add more "at a glance" data.

![image](https://user-images.githubusercontent.com/83078310/133149254-c83755df-b214-4933-89fe-9fd1899567d9.png)

**Comment by willrlin** [comment]
Was the minimum income field just part of Bloom's original table data?

@tomgebauer @kar-r-green for thoughts

**Comment by abbiefarr** [comment]
@willrlin yes, we've defaulted to it because it's included in Bloom. It has meaning for other jurisdictions, but not for Detroit.

**Comment by kar-r-green** [comment]
Agreed, we should remove / reword for Detroit. Thanks for flagging!
