### ISSUE TITLE
Contribute frontend filtering upstream

### ISSUE THREAD

**Issue by avaleske** [CityOfDetroit/bloom#565]
We should contribute out frontend filtering work upstream so we don't diverge too much from exygy

**Comment by willrlin** [comment]
Which work were you thinking of specifically here? @seanmalbert said they're not planning to use the filtering modal we've put in, but maybe there are some pieces of `ui-components` that are worth contributing?

**Comment by avaleske** [comment]
Good to know. I had been thinking we could contribute it as a starting point for them, or behind a feature flag, so the frontends don't diverge too much.

So maybe at least some of the helper code? We could talk to Sean more about what would be helpful.
