### ISSUE TITLE
Close down permissions for creating new entities

### ISSUE THREAD

**Issue by anders-schneider** [CityOfDetroit/bloom#57]
https://github.com/CityOfDetroit/bloom/pull/10 opened up permissions such that any logged-in user can create new properties and listings (through the data access API). This config lives in `backend/core/src/auth/authz_policy.csv` and the relevant lines are:

```
p, user, listing, true, create
```

and 

```
p, user, property, true, create
```

**We definitely must avoid launching with the permissions in their current state.**

The right answer here is probably to remove/change those two lines, so that only admins can create new listings and properties. And then create an admin user that can be used for e.g. importing listing data from HRD. It would also likely be useful to talk to the Exygy team about how they run their listings-importer script such that it has sufficient permissions.

Done criteria: only admins can create listings/properties.

**Comment by willrlin** [comment]
Consider as part of this task adding back in the test removed in PR #24.

**Comment by abbiefarr** [comment]
Exygy is building out some access controls in the near future. Referencing [this issue](https://github.com/bloom-housing/bloom/issues/1616):

> ...we need to create a distinction between public and partner users. Rather than create a simple flag, we can do this via role assignment. We currently have two roles in the system, admin and user (and technically anonymous). We can assign the admin and user roles to partner users and leave it so public users have no role.

So in the future, only partners will have roles, which will allow us to easily prevent public users from editing the database. I'm hoping to pick up this work from Exygy if it's not coming up soon on their roadmap.
