### ISSUE TITLE
Demo URLs don't support logging in

### ISSUE THREAD

**Issue by avaleske** [CityOfDetroit/bloom#58]
The clientside JS currently hits `localhost:3100` for auth and other data. This is fine for local development, as we can port forward from our dev machines to our laptops, but doesn't work if we want to share demo links with others.

We can probably use a webpack proxy or nextjs config to do url rewrites, and update the backend urls in the .env files to point to the same endpoint as the client, so URLs would just something like `main-site.com/backend/user/auth` instead of `localhost:3100/user/auth` and nextjs would redirect it to the backend itself.

See also:
https://nextjs.org/docs/api-reference/next.config.js/rewrites

**Comment by willrlin** [comment]
I found a variable that looks like it's already being used for this purpose by Heroku, but not documented in the .env.template: INCOMING_HOOK_BODY. I'm testing it now; then I'll update the docker-compose.
