### ISSUE TITLE
[Bug] "Apply Online" button on listing page raises an error

### ISSUE THREAD

**Issue by anders-schneider** [CityOfDetroit/bloom#588]
[REMEMBER: a bug should be understandable years later by someone who will never talk to the reporter or assignee.]

STEPS TO REPRODUCE:
1. Navigate to the individual-listing page for "New Center Commons"
2. Click "Apply Online" in the right rail

EXPECTED RESULTS:
- I'm not sure "Apply Online" should even appear for this listing? But if it should, that button should lead to some relevant online application

OBSERVED RESULTS:
![image](https://user-images.githubusercontent.com/8754454/134050191-0ef74b32-91eb-43bd-858a-504efc0a088c.png)

ADDITIONAL INFORMATION:

**Comment by willrlin** [comment]
It shouldn't be there; I need to remove the application methods on a few more seed listings.

**Comment by willrlin** [comment]
Actually, if you seeded this with the non-detroit seeds, (i.e. `yarn db:reseed`) then all listings get an application link that doesn't work.

**Comment by willrlin** [comment]
I don't really think it's worthwhile to fix that; when you seed it with `yarn db:reseed:detroit` only Oak Village should have an apply button with an external link that works.
