### ISSUE TITLE
Clarify language around "ADA Compliant" filter and reserved community type filter and pill

### ISSUE THREAD

**Issue by anders-schneider** [CityOfDetroit/bloom#591]
Work:

1. Change to "Reserved for: Special Needs" in the pill
2. Provide text explanation of ADA compliance (tooltip? text in the filter modal?)

Context:
Writing up some feedback from Gabe (based on a meeting with the city):

When we filter listings by "ADA Compliant" set to "Yes", there are at least two points of confusion:
- What does ADA compliant mean?
- Why do only some of the resulting listings have the "Special Needs" pill?

This ticket proposes two pieces of work to address them.

**Comment by avaleske** [comment]
Reworded title and ticket to clarify what's actionable.

@anders-schneider are these product/detroit requests or is this the starting point for discussion?

**Comment by anders-schneider** [comment]
Note from property management weekly sync: Gabe met with the City of Detroit Office of Disability Affairs and they recommended that we change "ADA Compliant" to "Accessible units" (b/c "ADA compliant doesn't mean anything").

Elen's point from a previous sync with a disability-focused CBO: ADA-compliant units aren't always accessible. So maybe "accessible" is misleading. (@elenm to add any detail here.)

So: we may want to change "ADA compliant" to "Accessible units", or find another term. This will likely only matter until we have the more structured disability filtering (i.e. "does this building have an elevator?").
