### ISSUE TITLE
Add banner to say "call properties to verify data/availability" if filtering is applied

### ISSUE THREAD

**Issue by anders-schneider** [CityOfDetroit/bloom#592]
Work:
For some listing filtering (particularly around wholly elderly and partially elderly listings), we may want to indicate to users that they should call the property management company to confirm that there are units available that match their filter criteria.

One way to surface that information: once a user clicks "apply filters", we could display a banner at the top of the page to say e.g. "please confirm with the property management that the listings have available units for people over the age of 62".

Context:
This is another ticket from the property management sync, based on an idea from @elenm and Gabe.

**Comment by avaleske** [comment]
@anders-schneider was this a product/detroit request, or an idea we should consider?
