### ISSUE TITLE
Bulleted Unit Details / Amenities

### ISSUE THREAD

**Issue by kar-r-green** [CityOfDetroit/bloom#597]
HRD requested easier-to-read bulleted list of Unit Details / Unit Amenities on the Listing Details view. 

Note: Additional data parsing required.

**Comment by jnowell** [comment]
Once #812 is done, we should have logic on the front-end that comma-separates amenity data and creates a separate bullet point for each amenity. If the amenity data isn't comma-separated, then we can simply display as is (e.g. the status quo).
