### ISSUE TITLE
[UX] More prominent logo, sub-header description, use of photos

### ISSUE THREAD

**Issue by kar-r-green** [CityOfDetroit/bloom#598]
HRD requests a more prominent logo / removal of the upper left Detroit Home Connect button. Sub-header description requested. Use of photos where possible.

Note: Photo content required. User testing may be also required to determine usability.

@tomgebauer for additional UX comments / feedback. Please feel free to break into separate issues if needed.

**Comment by willrlin** [comment]
Andy created separate issues to track this: #671 #672 #673 #674
