### ISSUE TITLE
Epic: Filtering

### ISSUE THREAD

**Issue by avaleske** [CityOfDetroit/bloom#63]
Tracking issue for all filtering tickets.

This contains high levels plans, thoughts, etc that should be broken out to smaller tickets later. Also links to design docs, mocks, etc.

Links:
Work is tracked in this epic: Filtering
And in this filtered view: [Backlog-Sprint Filtering](https://github.com/CityOfDetroit/bloom/projects/1?card_filter_query=label%3A%22epic%3A+filtering%22)
Mocks are at: [Figma](https://www.figma.com/file/wAhoXVmHRIJ2TyBKFVq2JY/Desktop-and-Mobile-Experiences?node-id=242%3A119)
Design Doc is in [Box](https://app.box.com/file/839071952572?s=81o8pu0vgtkyd8o7qejae7zpz4mahmhb)

Subtickets:
- [x] #69
- [x] #143
- [x] #161
- [x] #55
- [x] #61
- [x] #60
- [x] #59
- [x] #56
- [x] #54
- [x] #103
- [x] #102 
- [x] #324
- [x] #320
- [x] #321
- [x] #322 
- [x] #149
- [x] #192
- [x] #193
- [x] #202
- [x] #210
- [x] #240
- [x] #255
- [x] #258
- [x] #313
- [ ] #314
- [ ] #357
- [x] #365
- [x] #519 
- [ ] #520 
- [x] #524
- [x] #530
- [ ] #565
- [x] #566
- [x] #625
- [ ] #629

Current size estimate: 46 (out of date)

### Notes on future portions of work
- Design generalized ability to filter by different listing attributes
- Implement filtering
- Add ability to filter by some of the attributes we have prioritized for filtering

**Comment by willrlin** [comment]
For future reference: #210 has some info about the filtering itself and what that looks like when building the URL.

**Comment by GabeBenjamin** [comment]
Closing this since filtering is mostly complete
