### ISSUE TITLE
Availability should show 4 states

### ISSUE THREAD

**Issue by willrlin** [CityOfDetroit/bloom#633]
According to the PRD, we should show 4 states based on availability:
- Accepting Applications
- Waitlist Open
- Waitlist Closed
- Coming Soon

Right now, we only show `waitlist` or the actual number of available units. Open question:
- Do we represent the `Accepting Applications` state as a state on the listing or just use the presence of available units as an indicator?
- How do we represent the `Coming Soon` status? `ListingStatus` has a `pending` state that is used for drafts and filtered out for displaying on the frontend. We could add a state there.

**Comment by avaleske** [comment]
In the summary, value of the availability column is set to "waitlist" here:
https://github.com/CityOfDetroit/bloom/blob/6e91c9231bad636bfbf690845cb01dd4d0bdf210/ui-components/src/helpers/tableSummaries.tsx#L51-L61
which doesn't check the value of `listing.isWaitlistOpen`

**Comment by jnowell** [comment]
I covered the logic for the different availability statuses in the following 3 issues: #853, #855, and #856.
