### ISSUE TITLE
Decide how property managers or HRD will upload property photo

### ISSUE THREAD

**Issue by elenm** [CityOfDetroit/bloom#64]
Assumption: no way to delete the photos from the hosting service when not used anymore.

- [x] hosting strategy
- [x] validate assumption about deleting photos

**Comment by willrlin** [comment]
This may be blocked by connecting to Drupal for image/video hosting. See #43.

**Comment by willrlin** [comment]
Edgar said the image hosting should also come in as a part of the quotes from vendors for hosting the application.

**Comment by willrlin** [comment]
I think this is blocked until we get more information from the DoIT team regarding hosting status, which will happen on Tuesday, Aug 17.

**Comment by willrlin** [comment]
DoIT has contacted vendors, image hosting is a part of that quote.

**Comment by willrlin** [comment]
Integrating with the image hosting is tracked in #394 and blocked on getting the hosting itself. There are hooks in the edit listing form that we can use if the image exists to delete it from the cloud hosting, so I'll mention that in #394 and close this.
