### ISSUE TITLE
Import `Property.neighborhood` field

### ISSUE THREAD

**Issue by anders-schneider** [CityOfDetroit/bloom#673]
Our CSV import script currently doesn't import a listing's neighborhood (though almost all listings in the HRD spreadsheet have the "Neighborhood" column populated; this should be an easy change.

**Comment by anders-schneider** [comment]
Actually this may be blocked by the question of "how do we store/represent each listing's neighborhood" (happening in https://github.com/CityOfDetroit/bloom/issues/674)

**Comment by jnowell** [comment]
Is this still blocked? In #674, I mentioned that Safiya said we could just use the neighborhood data we currently have. Don't think there's any outstanding questions, but LMK if that's not the case.

**Comment by anders-schneider** [comment]
Awesome, thanks @jnowell! I don't see any other blockers - I'll start work on this
