### ISSUE TITLE
Landing page: add a "Neighborhoods" section

### ISSUE THREAD

**Issue by anders-schneider** [CityOfDetroit/bloom#674]
![image](https://user-images.githubusercontent.com/8754454/136268335-a51230f6-ea24-4054-8672-db37d04e5f03.png)

Work needed here:
- [ ] We need a way to retrieve the names of all neighborhoods.
   - Currently, `neighborhood` is just a string field within `Property`. Given that, I think the best way to retrieve a list of all neighborhoods is to issue a query for all listings, and extract all the neighborhood names from that (inefficient, because that request would return _all_ data about _all_ listings).
   - An alternative: extract `neighborhood` from the `Propert` entity, into its own entity. We could then have a `/neighborhoods` controller with a `GET` method defined that just returns all neighborhoods.
- [ ] Figure out how to order the neighborhoods in this section (maybe just randomly? or by which neighborhoods have the most listings?)
- [ ] Figure out if we want to show _all_ neighborhoods, or just a maximum of N
- [ ] Create a new React component called e.g. `NeighborhoodCard`. Although the mock above shows only an image for each neighborhood, other mocks have also included the neighborhood name overlaid on top of the image.
- [ ] Make it possible for the user to scroll left and right to see all neighborhoods

**Comment by anders-schneider** [comment]
Note: we don't currently have images corresponding to each neighborhood, so we may just want to put some sort of placeholder. (Once we do have images, it'd be good to store those in the new `Neighborhood` entity I'm proposing above.)

**Comment by willrlin** [comment]
Plus it would seem strange that the only way to filter on neighborhoods is to use the front page (since we removed it from the modal)

**Comment by willrlin** [comment]
No, I was hoping that neighborhoods mapped easily to zipcodes, but I guess not. I think this would be a question for @jnowell and Safiya then. If we assume that most properties will have the correct neighborhoods and that we hard code it, maybe we go with that. Or we could construct a District -> neighborhood mapping and show districts on the front page.

**Comment by GabeBenjamin** [comment]
Do we have mobile mocks for this design? I tried looking in the figma files but I can't find any. Do we know how we want this to look on narrower screens?

**Comment by willrlin** [comment]
I don't think Tom left any mobile mocks.
