### ISSUE TITLE
Add initial filtering capability to backend API

### ISSUE THREAD

**Issue by elenm** [CityOfDetroit/bloom#69]
Part of CityOfDetroit/bloom#63 

- [x] Add basic filter to backend request

Work on this is in feature/avaleske-initial-filters

Done: We can hit an API endpoint and get a filtered result back

(Moving frontend filter work to CityOfDetroit/bloom#55)

**Comment by willrlin** [comment]
It looks like Exygy is adding some optional query parameters in the /listings endpoint.

**Comment by willrlin** [comment]
I'm assuming you meant to close this since you moved it to the closed column.
