### ISSUE TITLE
[Copy Change] Edit Welcome message on Eligibility Questionnaire 

### ISSUE THREAD

**Issue by GabeBenjamin** [CityOfDetroit/bloom#690]
Edit Welcome message on Eligibility Questionnaire

![image](https://user-images.githubusercontent.com/371177/137976468-974138e1-3bcb-4758-ab3d-91d3f38e379b.png)

**Comment by jnowell** [comment]
Safiya just came through with the new wording. The 'Welcome' header should stay as is, and the content below should be "Welcome to Detroit Home Connect! We know that finding housing can be difficult. We are here to help. To find you a home that best fits your needs, let's answer four simple questions first. Some affordable housing only accepts people of certain ages or certain incomes, so we want to make sure you are applying to properties that work for your household."
