### ISSUE TITLE
"New Listing" Email/SMS Notifications tracking issue

### ISSUE THREAD

**Issue by GabeBenjamin** [CityOfDetroit/bloom#695]
Tracking issue for "New Listing"  Email/SMS Notifications

# Email
## Product questions
- [x] #700

## Eng
- [x] #696
- [x] #697
- [x] #699
- [ ] #698

# SMS
## Product questions
- [x] #706

## Eng
- [x] #701
- [x] #702
- [x] #703
- [x] #704
- [ ] #705

**Comment by YazeedLoonat** [comment]
closing!
