### ISSUE TITLE
[Email/SMS] Create queue/function to send email to users

### ISSUE THREAD

**Issue by GabeBenjamin** [CityOfDetroit/bloom#698]
What feature is this part of?
"New Listing" Email/SMS Notifications

**Comment by anders-schneider** [comment]
The current state of this: the framework for asynchronously sending notifications exists (and is in use for SMS notifications, #705), but no email notifications are currently being sent.

The remaining work (much of which will piggyback on the SMS-notification work):

- [ ] Trigger an email notification to each opted-in user when a new listing is created (and its status is "active").
- [ ] Trigger an email notification to each opted-in user when an existing listing's status changes to "active"

**Comment by YazeedLoonat** [comment]
closing!
