### ISSUE TITLE
Add 'Learn About Affordable Housing' Page

### ISSUE THREAD

**Issue by jnowell** [CityOfDetroit/bloom#729]
As part of our work to add static content to the site, we would like to add a 'Learn About Affordable Housing' page. This page will be linked from the header (exact link verbiage TBD). This page will host some videos that Safiya is currently reviewing. Once Safiya approves the videos and we decide on an exact link title I will unblock the bug and hand it over to Gabe.

**Comment by jnowell** [comment]
The title of the link on the header should be 'Learn More'. I'll send an update once the videos are reviewed and ready to be added.

**Comment by jnowell** [comment]
Safiya has reviewed the videos, but had a few thoughts about possible changes, so we'll work to resolve those. Once we've finalized videos, I'll update this bug.

**Comment by YazeedLoonat** [comment]
closing!
