### ISSUE TITLE
Add testing to exercise `POST /listings`

### ISSUE THREAD

**Issue by anders-schneider** [CityOfDetroit/bloom#771]
I don't think we have any tests that execute a `POST /listings` request. [The existing listings controller test](https://github.com/CityOfDetroit/bloom/blob/main/backend/core/src/listings/listings.controller.spec.ts) just verifies that the controller can be created.

This has caused problems for @aisiri-murulidhar and me: we have separate workflows that require the creation of a listing (through the controller) to trigger some process, and we're stuck with errors about e.g. "the `image` field must not be null/undefined when creating a listing". (In my case, I'm seeing these issues when I run the [import-listing-from-json-file.ts script](https://github.com/CityOfDetroit/bloom/blob/main/backend/core/scripts/import-listing-from-json-file.ts) with [minimal-listing.json](https://github.com/CityOfDetroit/bloom/blob/main/backend/core/scripts/minimal-listing.json) - that "minimal listing" JSON is no longer sufficient/valid to create a listing through the controller.)

There is also some work to do here to go back and figure out if certain fields that are currently required to create a listing should actually be required.

ccing @aisiri-murulidhar and @plunkettgoogle since we discussed together this morning.

**Comment by plunkettgoogle** [comment]
I think I found the culprit PR: https://github.com/bloom-housing/bloom/pull/1850. This added a lot of validation around creating listings, but I'm not sure why it's enforcing so many fields when they're marked `@IsOptional`.

**Comment by plunkettgoogle** [comment]
Oh, I think I understand now: that PR enforced that a bunch more fields be populated if the listing is "active" versus "draft", through the `statusToListingValidationModelMap` thingy in the `ListingCreateValidationPipe`.

I can update the `minimal_listing.json` to match the `ListingPublishedCreateDto` model instead, and add a test that uses that model.
