### ISSUE TITLE
Update Property Detail data to be comma-separated

### ISSUE THREAD

**Issue by jnowell** [CityOfDetroit/bloom#812]
As currently displayed, the Property Detail data is kind of jumbled together and hard to read (screenshot attached). It would be much easier to read if these amenities were comma-separated. We should update the data we have to make sure that this amenity data is comma-separated to make it easier to read. I'm happy to handle this, as long as I can get pointed to the appropriate file/SQL database (marking as blocked until I get that info).

![unit_amenities](https://user-images.githubusercontent.com/394908/145108427-eb6876a0-5b73-49f4-8c3a-8e290ca365e8.png)

**Comment by plunkettgoogle** [comment]
I can work on updating the seed scripts to comma separate these, but you can update these fields on the public deployment by going through the partner portal. The "Unit Amenities" field in the edit page controls this string.

**Comment by plunkettgoogle** [comment]
Actually, it actually looks like most of them are already comma separated. :thinking:
