### ISSUE TITLE
Propose a model for availability

### ISSUE THREAD

**Issue by elenm** [CityOfDetroit/bloom#84]
We've received feedback that it's important that we surface availability data in the public portal. However, there are still questions around what availability means and how we can surface that data in a way that's helpful for residents and appealing to property managers.

AIs for this ticket:
- [x] Concretely define "availability"
- [x]  Propose a corresponding data model that allows us to surface availability data

**Comment by abbiefarr** [comment]
Definition of availability: the # of currently unoccupied units in a listing/building

The proposal for surfacing this data is as follows:
*  Create a new table for units summaries. This will be used by both us and Exygy. 
* For Exygy, the table will be derived from the existing "units" table, similarly to how the existing unitsSummaries data type is being generated.
* For us, we may choose to build the summary table from a CSV import, or allow PMs to edit the table directly. That choice is TBD based on ongoing discussions with PMs.
* When surfacing availability information, we'll read directly from the new table.
