### ISSUE TITLE
[Bug] Sign in/Sign up on two lines

### ISSUE THREAD

**Issue by plunkettgoogle** [CityOfDetroit/bloom#866]
Not sure why, but on my machine, the "Sign in" and "Sign up" buttons are rendering across two lines of text:

![localhost_3000_eligibility_household (4)](https://user-images.githubusercontent.com/66751489/145900296-99122446-b271-4eaf-906e-f5e07d5bff60.png)

It's possible I modified the default text size in Chrome?

**Comment by plunkettgoogle** [comment]
Ah yes, I had set my font size to "Large" through "Settings" > "Appearance" > "Font Size" in Chrome.

Is this something we should adapt to?

**Comment by YazeedLoonat** [comment]
Looks to be resolved, closing
