### ISSUE TITLE
Remove Neighborhood box at bottom of Listing Detail page

### ISSUE THREAD

**Issue by jnowell** [CityOfDetroit/bloom#912]
There's currently a neighborhood box at the bottom of the Listing Detail page ([example](https://sites-public-tj3gg4i5eq-uc.a.run.app/listing/ff945428-fcd7-46bf-a290-3c9219039df1/oak_village_independence_4401_burlingame_st_detroit_mi)). The design of this box is a little odd (it ends up being partly in the footer) and adds no value, since the information is viewable elsewhere in the page. This section of the Listing Detail page should be removed.

![neighborhood_detail_box](https://user-images.githubusercontent.com/394908/147571279-d0b1fea6-159d-4217-a08f-bf7faff59e46.png)

**Comment by YazeedLoonat** [comment]
The lil box is tied to the mapbox map, closing since i think those should be paired together
