### ISSUE TITLE
Update partner portal to use new site header 

### ISSUE THREAD

**Issue by jnowell** [CityOfDetroit/bloom#915]
The partner portal is still using the outdated site header. Given that our user feedback showed people greatly preferred the [new header](https://detroit-public-dev.netlify.app/listings) being used in the public portal, we should make sure this header is persisted to the partner portal as well.

![partner_portal_header](https://user-images.githubusercontent.com/394908/147594421-33a8d45f-5f97-4331-abc5-410473286330.png)

**Comment by YazeedLoonat** [comment]
closing!
