### ISSUE TITLE
Update 'Unit Availability' filter

### ISSUE THREAD

**Issue by jnowell** [CityOfDetroit/bloom#917]
As outlined in #633, units have 4 different phase of availability: Accepting Applications, Waitlist Open, Waitlist Closed, and Pending. However, the current Unit Availability filter doesn't account for this, and currently only shows 3 options: Has Availability, No Availability, and Waitlist. We should update the dropdown to have the following 3 options:

Coming Soon
Waitlist Open
Waitlist Closed

'Coming Soon' should correlate to any property that has available units (see #855).  'Waitlist Open' and 'Waitlist Closed' should pertain to non-pending properties without availability (see #853 for how to determine whether a property is considered 'Waitlist Open' or 'Waitlist Closed'. Meanwhile, Pending units (see #856) should be disregarded from the dropdown, as it would just cause confusion.

![unit_avail_filter](https://user-images.githubusercontent.com/394908/147597164-df054c2b-2f64-4984-b6fb-eef672ea4b03.png)

**Comment by YazeedLoonat** [comment]
the filter has been reworked since this was written, closing
