### ISSUE TITLE
Populate 'Housing Preferences' section of partner portal

### ISSUE THREAD

**Issue by jnowell** [CityOfDetroit/bloom#920]
In the partner portal, when you go to the Edit Listing page, there's a section for Housing Preferences. When you click the 'Add Preferences' button, there's a 'Select Preferences' button you can click, but there's no actual preferences that you can select. While the short-term solution is to simply remove this section (see #919), ultimately what we'd like to do is populate this section with preferences that the property manager can select.

First step would be to determine which exact preferences we should add.
 
![housing_preferences_selection](https://user-images.githubusercontent.com/394908/147664823-9a1cb61e-801f-4813-bf43-4a5374986d34.png)

**Comment by YazeedLoonat** [comment]
closing!
