### ISSUE TITLE
Notify residents when availability of property is updated.

### ISSUE THREAD

**Issue by jnowell** [CityOfDetroit/bloom#921]
Aside from notifying residents when a new listing is added, we'd also like to notify them when the availability of a listing is updated. We will probably want to trigger the notification when a listing goes from 'Waitlist Closed' to 'Waitlist Open' or when a property goes from 0 availability to having an available unit. However, this exact logic needs to be confirmed before implementing.

**Comment by YazeedLoonat** [comment]
closing!
