### ISSUE TITLE
Build script to ingest availability data from Bostonpost

### ISSUE THREAD

**Issue by jnowell** [CityOfDetroit/bloom#922]
Premier Property Management is one of the 6 property management companies we've targeted as key partners to build our availability automation functionality. So far, they've been the only one that uses [Bostonpost](https://www.mrisoftware.com/resources/bostonpost/) to manage their availability data. We need to write an ingestion script (similar to the one plunkettgoogle wrote for RealPage) that allows us to take a data export from Bostonpost and convert it to data that can be ingested into Bloom.

The data export requires the number of available units for each property, broken down by unit type and AMI threshold. Unfortunately, from going back and forth with our contact at Premier, the only data export they have that provides all this data is an XLS file. We'd greatly prefer this data in a format like XML, but the problem is the analagous XML file doesn't include the Community Name, so there's no way to map the data to its respective property. Both Detroit and Premier have contacts with Bostonpost, so we're hoping that they can reach out and see if there are any options to add this data to the XML file (or find some other solution to the problem), but at the moment we're not very optimistic that anything will come of that (Bostonpost doesn't really update their data exporting options).

So, barring an unexpected change, the best approach is to move forward with writing a script to ingest the data from the XLS file. I'm attaching an example we received from our contact at Premier. As I see it, it should be possible to write a script that ingests this data using the following approach:

- Go through the spreadsheet line-by-line
- When we get to a new property (e.g. Avon Park Apartments) make sure we store the property name. 
- For each line of reporting data, when we see that column D (Tenant Name) is '--VACANT--', look at column L (Set Aside) and column Q (HH Size) to get the AMI threshold as well as Unit Type. Keep a running tally for each (HH Size, Set Aside) pair.
- When we get to the end of the reporting data, make note of the total # of available units for each HH Size/AMI pair (e.g. how many 1-bedroom 40% AMI units are available).
- Ignore the summary data, and move on to the next property.

I'd hope long-term we could develop a less fragile approach, but I think this could work as a short-to-medium term soluion.

[ppm-community-rent-roll.xls](https://github.com/CityOfDetroit/bloom/files/7789784/ppm-community-rent-roll.xls)

**Comment by YazeedLoonat** [comment]
closing, this may need to be looked at in the future but a more general data ingestion approach needs to be built out first
