### ISSUE TITLE
Develop strategy to automate delivery of Bostonpost data

### ISSUE THREAD

**Issue by jnowell** [CityOfDetroit/bloom#924]
Once we have a script that can ingest data from Bostonpost into Bloom (see #922), we need to develop a strategy on how to automate ingestion of the data so that we reliably receive it once a day. Issue #923 outlines the approach we're taking with RealPage. It's possible that a similar approach will work with Bostonpost, but we'll have to work with our contact at Premier to determine if this is the case. Once we've established with him a solution for ingesting data, we can tackle this issue and see what our options are.

**Comment by YazeedLoonat** [comment]
closing!
