### ISSUE TITLE
Epic: Data Architecture

### ISSUE THREAD

**Issue by willrlin** [CityOfDetroit/bloom#95]
Tickets related to data syncing, fields in the database, etc.

- [x] #46
- [x] #50
- [x] #51
- [x] #67
- [x] #84
- [x] #88
- [x] #122
- [x] #123
- [x] #228
- [x] #229
- [x] #230
- [x] #231
- [x] #232

Current size (with some tasks not estimated): 24

**Comment by abbiefarr** [comment]
Are residents ever applying for a specific unit? Or are they applying to get on a waitlist? Or both?

**Comment by willrlin** [comment]
Next steps:
- write up some kind of implementation plan
- send to exygy for feedback
- they slice by different things for summaries - derived unit summaries not just by # of BR, but also by a number of other fields
- get our detroit site working first? risk vs working in bloom first
