### ISSUE TITLE
Epic: Eligibility Questionnaire

### ISSUE THREAD

**Issue by willrlin** [CityOfDetroit/bloom#96]
Tickets related to the eligibility questionnaire.

- [ ] #79
- [x] #85
- [x] #118
- [x] #119
- [x] #120
- [ ] #121
- [x] #205 
- [x] #215 
- [x] #216 
- [ ] #217 
- [x] #218 
- [x] #219 
- [x] #224 
- [x] #225

**Comment by willrlin** [comment]
Tom, are we no longer doing the eligibility questionnaire style at all? Or is that still in flux?

**Comment by willrlin** [comment]
@tomgebauer let me know where it was in the wireframes - I just missed the entry point.

**Comment by tomgebauer** [comment]
Mockups for the Version 1.x of eligibility questionnaire can be found [here](https://www.figma.com/file/wAhoXVmHRIJ2TyBKFVq2JY/Desktop-and-Mobile-Experiences?node-id=1521%3A5014).
