### ISSUE TITLE
Accessibility Audit: Improper announcement for the "City of Detroit" graphic

### ISSUE THREAD

**Issue by jnowell** [CityOfDetroit/bloom#963]
ENVIRONMENT
Mobile: OS | OS Ver | Assistive Technology
Pixel 3a XL | Android 12 | Talk Back

PREREQUISITES
Ensure the Screen Reader is on, and go to the [homepage](https://homeconnect.detroitmi.gov/). Navigate to the "City of Detroit" logo and observe the screen reader announcement. As you can see in the attached video, the announcement for the "City of Detroit" icon is "Site Logo Graphic icon". The focus should not be shown on the "Site logo" icon as it is not rendering any meaningful information to the user, all the icons which are decorative should not have the focus.

NOTE: I was not able to replicate this in Voiceover in a Chrome on my Macbook.

https://user-images.githubusercontent.com/394908/148608116-f512442d-c076-451e-9343-aa52f61007ef.mp4

**Comment by ColinBuyck** [comment]
No longer valid
