### ISSUE TITLE
Detroit: Remove Required Fields

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#969]
As a partner in Detroit, 
I don't want the same required fields as in other jurisdictions because my listings will be more open 

**Acceptance Criteria** 
* When I save as a draft, I should only have Name and Jurisdiction as a required field
* When I try to publish a listing, I should only have the same required fields as for saving a draft 

**Notes**
* What else is required for draft right now? Address? 
* Might be simplest to just change published validators to save as draft ones

**Comment by dominikx96** [comment]
@pbn4 frontend work is covered by: https://github.com/CityOfDetroit/bloom/pull/985

**Comment by kathyccheng** [comment]
LGTM
