### ISSUE TITLE
Detroit: Show mapbox on listing detail page

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#976]
**Acceptance Criteria**
* When I'm on the listing page, then I should see a map showing me where the address is 

**Notes**
* Add mapbox back in, bring over what's in core to their detail page

**Comment by jaredcwhite** [comment]
After some investigation, I discovered the MapBox code is actually still there in the listing view, but they must not have a MapBox API token set up for the hosting provider (Netlify?). In local dev I added our usual API token and it works, as you can see:

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/658496/153337739-c8740843-9fde-4112-ad66-68e5e4169bf8.png">

**Comment by seanmalbert** [comment]
Map is now showing on https://detroit-public-dev.netlify.app/ and https://detroit-partners-dev.netlify.app/

![Screen Shot 2022-02-12 at 10 28 10 AM](https://user-images.githubusercontent.com/4401157/153721573-e3a7d665-8801-4345-92d5-e97ef31e99e5.png)
