### ISSUE TITLE
Add staging environement for Detroit

### ISSUE THREAD

**Issue by kathyccheng** [CityOfDetroit/bloom#993]
We'll have 

Dev
Staging (proxy for production)

Pin all environments in Detroit + Eng Channels

**Comment by seanmalbert** [comment]
Got environments setup, just need Edgar to connect the Heroku app to the repository and I'll finish it up.

**Comment by seanmalbert** [comment]
staging/prod setup at https://detroit-public-prod.netlify.app/ and https://detroit-partners-prod.netlify.app/

**Comment by kathyccheng** [comment]
LGTM
